// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  AttributeActionData,
  AttributeActionErrors,
  AttributeActionResponses,
  CreateCancelDepositInteractionData,
  CreateCancelDepositInteractionErrors,
  CreateCancelDepositInteractionResponses,
  CreateClaimDepositInteractionData,
  CreateClaimDepositInteractionErrors,
  CreateClaimDepositInteractionResponses,
  CreateDepositInteractionData,
  CreateDepositInteractionErrors,
  CreateDepositInteractionResponses,
  CreateWithdrawInteractionData,
  CreateWithdrawInteractionErrors,
  CreateWithdrawInteractionResponses,
  VerifyTrackingData,
  VerifyTrackingErrors,
  VerifyTrackingResponses,
} from "../types.gen";

/**
 * Attribute Action Handler
 *
 * [DEPRECATED] Attribute a transaction hash to an action. Attribution is now handled automatically by the Lumon collector.
 */
export const attributeAction = <ThrowOnError extends boolean = false>(
  options: Options<AttributeActionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AttributeActionResponses,
    AttributeActionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/attribute/{actionId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Cancel Deposit Interaction Handler
 *
 * Cancel a pending async deposit.
 */
export const createCancelDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCancelDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCancelDepositInteractionResponses,
    CreateCancelDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/cancel-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Claim Deposit Interaction Handler
 *
 * Claim a pending async deposit. Only requires user wallet address.
 */
export const createClaimDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateClaimDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateClaimDepositInteractionResponses,
    CreateClaimDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/claim-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Interaction Handler
 *
 * Record a deposit interaction
 */
export const createDepositInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDepositInteractionResponses,
    CreateDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify Tracking Handler
 *
 * Verify tracking data in a transaction
 */
export const verifyTracking = <ThrowOnError extends boolean = false>(
  options: Options<VerifyTrackingData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    VerifyTrackingResponses,
    VerifyTrackingErrors,
    ThrowOnError
  >({ url: "/v1/actions/verify", ...options });

/**
 * Create Withdraw Interaction Handler
 *
 * Record a withdraw interaction
 */
export const createWithdrawInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateWithdrawInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateWithdrawInteractionResponses,
    CreateWithdrawInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/withdraw/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
