// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetWalletActivityData,
  GetWalletActivityErrors,
  GetWalletActivityResponses,
} from "../types.gen";
import {
  zGetWalletActivityQuery,
  zGetWalletActivityResponse,
} from "../zod.gen";

/**
 * Get Wallet Activity Handler
 *
 * Get paginated verified earn interactions for the given wallet addresses (comma-separated), ordered by date descending.
 */
export const getWalletActivity = <ThrowOnError extends boolean = false>(
  options?: Options<GetWalletActivityData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetWalletActivityResponses,
    GetWalletActivityErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetWalletActivityQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetWalletActivityResponse.parseAsync(data),
    url: "/v1/wallets/activity/",
    ...options,
  });
