// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  AttributeActionData,
  AttributeActionErrors,
  AttributeActionResponses,
  CreateCancelDepositInteractionData,
  CreateCancelDepositInteractionErrors,
  CreateCancelDepositInteractionResponses,
  CreateClaimDepositInteractionData,
  CreateClaimDepositInteractionErrors,
  CreateClaimDepositInteractionResponses,
  CreateDepositInteractionData,
  CreateDepositInteractionErrors,
  CreateDepositInteractionResponses,
  CreateWithdrawInteractionData,
  CreateWithdrawInteractionErrors,
  CreateWithdrawInteractionResponses,
  VerifyTrackingData,
  VerifyTrackingErrors,
  VerifyTrackingResponses,
} from "../types.gen";
import {
  zAttributeActionBody,
  zAttributeActionPath,
  zAttributeActionResponse,
  zCreateCancelDepositInteractionBody,
  zCreateCancelDepositInteractionPath,
  zCreateCancelDepositInteractionResponse,
  zCreateClaimDepositInteractionBody,
  zCreateClaimDepositInteractionPath,
  zCreateClaimDepositInteractionResponse,
  zCreateDepositInteractionBody,
  zCreateDepositInteractionPath,
  zCreateDepositInteractionResponse,
  zCreateWithdrawInteractionBody,
  zCreateWithdrawInteractionPath,
  zCreateWithdrawInteractionResponse,
  zVerifyTrackingQuery,
  zVerifyTrackingResponse,
} from "../zod.gen";

/**
 * Attribute Action Handler
 *
 * [DEPRECATED] Attribute a transaction hash to an action. Attribution is now handled automatically by the Lumon collector.
 */
export const attributeAction = <ThrowOnError extends boolean = false>(
  options: Options<AttributeActionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AttributeActionResponses,
    AttributeActionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zAttributeActionBody.optional(),
          path: zAttributeActionPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zAttributeActionResponse.parseAsync(data),
    url: "/v1/actions/attribute/{actionId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Cancel Deposit Interaction Handler
 *
 * Cancel a pending async deposit.
 */
export const createCancelDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCancelDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCancelDepositInteractionResponses,
    CreateCancelDepositInteractionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateCancelDepositInteractionBody.optional(),
          path: zCreateCancelDepositInteractionPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateCancelDepositInteractionResponse.parseAsync(data),
    url: "/v1/actions/cancel-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Claim Deposit Interaction Handler
 *
 * Claim a pending async deposit. Only requires user wallet address.
 */
export const createClaimDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateClaimDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateClaimDepositInteractionResponses,
    CreateClaimDepositInteractionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateClaimDepositInteractionBody.optional(),
          path: zCreateClaimDepositInteractionPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateClaimDepositInteractionResponse.parseAsync(data),
    url: "/v1/actions/claim-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Interaction Handler
 *
 * Record a deposit interaction
 */
export const createDepositInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDepositInteractionResponses,
    CreateDepositInteractionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateDepositInteractionBody.optional(),
          path: zCreateDepositInteractionPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateDepositInteractionResponse.parseAsync(data),
    url: "/v1/actions/deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify Tracking Handler
 *
 * Verify tracking data in a transaction
 */
export const verifyTracking = <ThrowOnError extends boolean = false>(
  options: Options<VerifyTrackingData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    VerifyTrackingResponses,
    VerifyTrackingErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zVerifyTrackingQuery,
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zVerifyTrackingResponse.parseAsync(data),
    url: "/v1/actions/verify",
    ...options,
  });

/**
 * Create Withdraw Interaction Handler
 *
 * Record a withdraw interaction
 */
export const createWithdrawInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateWithdrawInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateWithdrawInteractionResponses,
    CreateWithdrawInteractionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateWithdrawInteractionBody.optional(),
          path: zCreateWithdrawInteractionPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateWithdrawInteractionResponse.parseAsync(data),
    url: "/v1/actions/withdraw/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
