// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetDistributorDepositsData,
  GetDistributorDepositsErrors,
  GetDistributorDepositsResponses,
} from "../types.gen";

/**
 * Get Distributor Deposits Handler
 *
 * Get paginated verified deposit interactions for a specific distributor, ordered by date descending. Optionally filter by opportunity_id and/or product_id.
 */
export const getDistributorDeposits = <ThrowOnError extends boolean = false>(
  options: Options<GetDistributorDepositsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDistributorDepositsResponses,
    GetDistributorDepositsErrors,
    ThrowOnError
  >({ url: "/v1/deposit/{distributor_id}", ...options });
