// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetDepositsData,
  GetDepositsErrors,
  GetDepositsResponses,
} from "../types.gen";

/**
 * Get Deposits Handler
 *
 * Get deposit transactions for a specific distributor
 */
export const getDeposits = <ThrowOnError extends boolean = false>(
  options: Options<GetDepositsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDepositsResponses,
    GetDepositsErrors,
    ThrowOnError
  >({ url: "/v1/deposit/{distributor_id}", ...options });
