// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetDistributorDepositsData,
  GetDistributorDepositsErrors,
  GetDistributorDepositsResponses,
} from "../types.gen";
import {
  zGetDistributorDepositsPath,
  zGetDistributorDepositsQuery,
  zGetDistributorDepositsResponse,
} from "../zod.gen";

/**
 * Get Distributor Deposits Handler
 *
 * Get paginated verified deposit interactions for a specific distributor, ordered by date descending. Optionally filter by opportunity_id and/or product_id.
 */
export const getDistributorDeposits = <ThrowOnError extends boolean = false>(
  options: Options<GetDistributorDepositsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDistributorDepositsResponses,
    GetDistributorDepositsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetDistributorDepositsPath,
          query: zGetDistributorDepositsQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetDistributorDepositsResponse.parseAsync(data),
    url: "/v1/deposit/{distributor_id}",
    ...options,
  });
