// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetEarnSwapData,
  GetEarnSwapErrors,
  GetEarnSwapResponses,
  GetSwapDetailsData,
  GetSwapDetailsErrors,
  GetSwapDetailsResponses,
  GetSwapTokensData,
  GetSwapTokensErrors,
  GetSwapTokensResponses,
} from "../types.gen";

/**
 * Get Swap Handler
 *
 * Build approve + swap transactions via the router for an arbitrary token pair
 */
export const getEarnSwap = <ThrowOnError extends boolean = false>(
  options: Options<GetEarnSwapData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEarnSwapResponses,
    GetEarnSwapErrors,
    ThrowOnError
  >({ url: "/v1/swap/", ...options });

/**
 * Get Swap Details Handler
 *
 * Static-ish swap picker data: supported chains plus popular tokens for the selected chain
 */
export const getSwapDetails = <ThrowOnError extends boolean = false>(
  options?: Options<GetSwapDetailsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSwapDetailsResponses,
    GetSwapDetailsErrors,
    ThrowOnError
  >({ url: "/v1/swap/details", ...options });

/**
 * Get Swap Tokens Handler
 *
 * Search swap tokens for a chain. Partial match on symbol/name/address against the curated catalog, with an Enso fallback (by address or exact symbol) when the catalog has no result
 */
export const getSwapTokens = <ThrowOnError extends boolean = false>(
  options: Options<GetSwapTokensData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSwapTokensResponses,
    GetSwapTokensErrors,
    ThrowOnError
  >({ url: "/v1/swap/tokens", ...options });
