// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  CreateMembershipAgreementData,
  CreateMembershipAgreementErrors,
  CreateMembershipAgreementResponses,
  GetMembershipData,
  GetMembershipResponses,
  MembershipCreateData,
  MembershipCreateErrors,
  MembershipCreateResponses,
} from "../types.gen";

/**
 * Check Membership
 *
 * Check if a wallet address is associated with a user
 */
export const getMembership = <ThrowOnError extends boolean = false>(
  options?: Options<GetMembershipData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMembershipResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/membership/", ...options });

/**
 * Create Membership
 *
 * Create a new user and associate wallet (signup only, no session)
 */
export const membershipCreate = <ThrowOnError extends boolean = false>(
  options?: Options<MembershipCreateData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    MembershipCreateResponses,
    MembershipCreateErrors,
    ThrowOnError
  >({
    url: "/v1/membership/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Create Membership Agreement
 *
 * Generate a message to be signed by a new wallet for signup
 */
export const createMembershipAgreement = <ThrowOnError extends boolean = false>(
  options?: Options<CreateMembershipAgreementData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateMembershipAgreementResponses,
    CreateMembershipAgreementErrors,
    ThrowOnError
  >({
    url: "/v1/membership/agreement",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
