// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  CreateMembershipAgreementData,
  CreateMembershipAgreementErrors,
  CreateMembershipAgreementResponses,
  GetMembershipData,
  GetMembershipResponses,
  MembershipCreateData,
  MembershipCreateErrors,
  MembershipCreateResponses,
} from "../types.gen";
import {
  zCreateMembershipAgreementBody,
  zCreateMembershipAgreementResponse,
  zGetMembershipQuery,
  zGetMembershipResponse,
  zMembershipCreateBody,
  zMembershipCreateResponse,
} from "../zod.gen";

/**
 * Check Membership
 *
 * Check if a wallet address is associated with a user
 */
export const getMembership = <ThrowOnError extends boolean = false>(
  options?: Options<GetMembershipData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMembershipResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetMembershipQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetMembershipResponse.parseAsync(data),
    url: "/v1/membership/",
    ...options,
  });

/**
 * Create Membership
 *
 * Create a new user and associate wallet (signup only, no session)
 */
export const membershipCreate = <ThrowOnError extends boolean = false>(
  options?: Options<MembershipCreateData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    MembershipCreateResponses,
    MembershipCreateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zMembershipCreateBody.optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zMembershipCreateResponse.parseAsync(data),
    url: "/v1/membership/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Create Membership Agreement
 *
 * Generate a message to be signed by a new wallet for signup
 */
export const createMembershipAgreement = <ThrowOnError extends boolean = false>(
  options?: Options<CreateMembershipAgreementData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateMembershipAgreementResponses,
    CreateMembershipAgreementErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateMembershipAgreementBody.optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateMembershipAgreementResponse.parseAsync(data),
    url: "/v1/membership/agreement",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
