// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetOpportunitiesByDistributorData,
  GetOpportunitiesByDistributorErrors,
  GetOpportunitiesByDistributorResponses,
  GetOpportunitiesData,
  GetOpportunitiesErrors,
  GetOpportunitiesResponses,
  GetOpportunityByIdData,
  GetOpportunityByIdErrors,
  GetOpportunityByIdResponses,
} from "../types.gen";

/**
 * Get Opportunities Handler
 *
 * Get opportunities with simplified token information
 */
export const getOpportunities = <ThrowOnError extends boolean = false>(
  options?: Options<GetOpportunitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetOpportunitiesResponses,
    GetOpportunitiesErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/", ...options });

/**
 * Get Opportunities By Distributor Handler
 *
 * Get opportunities for a specific distributor based on their earn details configuration
 */
export const getOpportunitiesByDistributor = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOpportunitiesByDistributorData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunitiesByDistributorResponses,
    GetOpportunitiesByDistributorErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/distributors/{distributor_id}", ...options });

/**
 * Get Opportunity By ID Handler
 *
 * Get a single opportunity by ID with simplified token information
 */
export const getOpportunityById = <ThrowOnError extends boolean = false>(
  options: Options<GetOpportunityByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunityByIdResponses,
    GetOpportunityByIdErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/{id}", ...options });
