// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  GetOpportunitiesByDistributorData,
  GetOpportunitiesByDistributorErrors,
  GetOpportunitiesByDistributorResponses,
  GetOpportunitiesData,
  GetOpportunitiesErrors,
  GetOpportunitiesResponses,
  GetOpportunityByIdData,
  GetOpportunityByIdErrors,
  GetOpportunityByIdResponses,
} from "../types.gen";
import {
  zGetOpportunitiesByDistributorPath,
  zGetOpportunitiesByDistributorResponse,
  zGetOpportunitiesQuery,
  zGetOpportunitiesResponse,
  zGetOpportunityByIdPath,
  zGetOpportunityByIdResponse,
} from "../zod.gen";

/**
 * Get Opportunities Handler
 *
 * Get opportunities with simplified token information
 */
export const getOpportunities = <ThrowOnError extends boolean = false>(
  options?: Options<GetOpportunitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetOpportunitiesResponses,
    GetOpportunitiesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetOpportunitiesQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetOpportunitiesResponse.parseAsync(data),
    url: "/v1/opportunities/",
    ...options,
  });

/**
 * Get Opportunities By Distributor Handler
 *
 * Get opportunities for a specific distributor based on their earn details configuration
 */
export const getOpportunitiesByDistributor = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOpportunitiesByDistributorData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunitiesByDistributorResponses,
    GetOpportunitiesByDistributorErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetOpportunitiesByDistributorPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetOpportunitiesByDistributorResponse.parseAsync(data),
    url: "/v1/opportunities/distributors/{distributor_id}",
    ...options,
  });

/**
 * Get Opportunity By ID Handler
 *
 * Get a single opportunity by ID with simplified token information
 */
export const getOpportunityById = <ThrowOnError extends boolean = false>(
  options: Options<GetOpportunityByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunityByIdResponses,
    GetOpportunityByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetOpportunityByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetOpportunityByIdResponse.parseAsync(data),
    url: "/v1/opportunities/{id}",
    ...options,
  });
