// This file is auto-generated by @hey-api/openapi-ts

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import type {
  V1StreamsCreatePointHandlerData,
  V1StreamsCreatePointHandlerErrors,
  V1StreamsCreatePointHandlerResponses,
  V1StreamsCreateStreamHandlerData,
  V1StreamsCreateStreamHandlerErrors,
  V1StreamsCreateStreamHandlerResponses,
  V1StreamsGetPointsHandlerData,
  V1StreamsGetPointsHandlerErrors,
  V1StreamsGetPointsHandlerResponses,
  V1StreamsGetStreamsHandlerData,
  V1StreamsGetStreamsHandlerErrors,
  V1StreamsGetStreamsHandlerResponses,
  V1StreamsGetTokensHandlerData,
  V1StreamsGetTokensHandlerErrors,
  V1StreamsGetTokensHandlerResponses,
  V1StreamsGetWalletHandlerData,
  V1StreamsGetWalletHandlerErrors,
  V1StreamsGetWalletHandlerResponses,
  V1StreamsGetWalletsHandlerData,
  V1StreamsGetWalletsHandlerErrors,
  V1StreamsGetWalletsHandlerResponses,
} from "../types.gen";

/**
 * Get Streams Data
 *
 * Get streams for the organization associated with the API key, optionally filtered by stream ID and with optional snapshots.
 */
export const v1StreamsGetStreams = <ThrowOnError extends boolean = false>(
  options?: Options<V1StreamsGetStreamsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    V1StreamsGetStreamsHandlerResponses,
    V1StreamsGetStreamsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/", ...options });

/**
 * Create Stream with API Key Authentication
 *
 * Handle create stream and signature request
 */
export const v1StreamsCreateStream = <ThrowOnError extends boolean = false>(
  options?: Options<V1StreamsCreateStreamHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    V1StreamsCreateStreamHandlerResponses,
    V1StreamsCreateStreamHandlerErrors,
    ThrowOnError
  >({
    url: "/v1/streams/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get Stream Points
 *
 * Get the points that belong to the organization associated with the API key.
 */
export const v1StreamsGetPoints = <ThrowOnError extends boolean = false>(
  options?: Options<V1StreamsGetPointsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    V1StreamsGetPointsHandlerResponses,
    V1StreamsGetPointsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/points", ...options });

/**
 * Create Stream Point
 *
 * Create a point for the organization associated with the API key.
 */
export const v1StreamsCreatePoint = <ThrowOnError extends boolean = false>(
  options?: Options<V1StreamsCreatePointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    V1StreamsCreatePointHandlerResponses,
    V1StreamsCreatePointHandlerErrors,
    ThrowOnError
  >({
    url: "/v1/streams/points",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get Stream Tokens
 *
 * Get all supported tokens for a chain that can be used for streams.
 */
export const v1StreamsGetTokens = <ThrowOnError extends boolean = false>(
  options: Options<V1StreamsGetTokensHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetTokensHandlerResponses,
    V1StreamsGetTokensHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/tokens", ...options });

/**
 * Get Stream Wallets
 *
 * Retrieve the wallets participating in a stream along with their latest snapshot data.
 *
 * **Pagination:**
 * - Use 'page' (default: 1) and 'limit' (default: 20) query parameters.
 * - Results are ordered by rewardsAccumulated descending.
 *
 * **Note:**
 * - rewardsAccumulated and rewardsAccumulatedBase are represented in wei units.
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWallets = <ThrowOnError extends boolean = false>(
  options: Options<V1StreamsGetWalletsHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetWalletsHandlerResponses,
    V1StreamsGetWalletsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/{id}/wallets", ...options });

/**
 * Get Stream Wallet Data
 *
 * Retrieve all reward snapshots accumulated by a wallet for a specific stream.
 *
 * **Note:**
 * - The following fields are represented in wei units:
 * - wallet.snapshots[].rewardsAccumulated
 * - wallet.stream.totalAmount
 * - wallet.stream.lastSnapshot.amountDistributed
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWallet = <ThrowOnError extends boolean = false>(
  options: Options<V1StreamsGetWalletHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetWalletHandlerResponses,
    V1StreamsGetWalletHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/{id}/wallets/{address}", ...options });
