// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  type Options,
  v2GetChains,
  v2GetOpportunityHistorical,
  v2GetOpportunityHistoricalApr,
  v2GetOpportunityHistoricalApy,
  v2GetOpportunityHistoricalSharePrice,
  v2GetOpportunityHistoricalTvl,
  v2GetProtocols,
  v2GetTokenByAddress,
  v2GetTokens,
} from "../sdk.gen";
import type {
  HandlersV2GetChainsHandlerData,
  HandlersV2GetChainsHandlerError,
  HandlersV2GetChainsHandlerResponse,
  HandlersV2GetOpportunityHistoricalAprHandlerData,
  HandlersV2GetOpportunityHistoricalAprHandlerError,
  HandlersV2GetOpportunityHistoricalAprHandlerResponse,
  HandlersV2GetOpportunityHistoricalApyHandlerData,
  HandlersV2GetOpportunityHistoricalApyHandlerError,
  HandlersV2GetOpportunityHistoricalApyHandlerResponse,
  HandlersV2GetOpportunityHistoricalHandlerData,
  HandlersV2GetOpportunityHistoricalHandlerError,
  HandlersV2GetOpportunityHistoricalHandlerResponse,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerData,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerError,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerResponse,
  HandlersV2GetOpportunityHistoricalTvlHandlerData,
  HandlersV2GetOpportunityHistoricalTvlHandlerError,
  HandlersV2GetOpportunityHistoricalTvlHandlerResponse,
  HandlersV2GetProtocolsHandlerData,
  HandlersV2GetProtocolsHandlerError,
  HandlersV2GetProtocolsHandlerResponse,
  HandlersV2GetTokenByAddressHandlerData,
  HandlersV2GetTokenByAddressHandlerError,
  HandlersV2GetTokenByAddressHandlerResponse,
  HandlersV2GetTokensHandlerData,
  HandlersV2GetTokensHandlerError,
  HandlersV2GetTokensHandlerResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const handlersV2GetChainsHandlerQueryKey = (
  options?: Options<HandlersV2GetChainsHandlerData>,
) => createQueryKey("handlersV2GetChainsHandler", options);

/**
 * Get Supported Chains
 *
 * Returns all supported chains with pagination. Chains are filtered to active status only.
 */
export const handlersV2GetChainsHandlerOptions = (
  options?: Options<HandlersV2GetChainsHandlerData>,
) =>
  queryOptions<
    HandlersV2GetChainsHandlerResponse,
    HandlersV2GetChainsHandlerError,
    HandlersV2GetChainsHandlerResponse,
    ReturnType<typeof handlersV2GetChainsHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetChains({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetChainsHandlerQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const handlersV2GetChainsHandlerInfiniteQueryKey = (
  options?: Options<HandlersV2GetChainsHandlerData>,
): QueryKey<Options<HandlersV2GetChainsHandlerData>> =>
  createQueryKey("handlersV2GetChainsHandler", options, true);

/**
 * Get Supported Chains
 *
 * Returns all supported chains with pagination. Chains are filtered to active status only.
 */
export const handlersV2GetChainsHandlerInfiniteOptions = (
  options?: Options<HandlersV2GetChainsHandlerData>,
) =>
  infiniteQueryOptions<
    HandlersV2GetChainsHandlerResponse,
    HandlersV2GetChainsHandlerError,
    InfiniteData<HandlersV2GetChainsHandlerResponse>,
    QueryKey<Options<HandlersV2GetChainsHandlerData>>,
    | number
    | Pick<
        QueryKey<Options<HandlersV2GetChainsHandlerData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<HandlersV2GetChainsHandlerData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await v2GetChains({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: handlersV2GetChainsHandlerInfiniteQueryKey(options),
    },
  );

export const handlersV2GetOpportunityHistoricalHandlerQueryKey = (
  options: Options<HandlersV2GetOpportunityHistoricalHandlerData>,
) => createQueryKey("handlersV2GetOpportunityHistoricalHandler", options);

/**
 * Get Vault Historical Data
 *
 * Get combined historical time-series (TVL, share price, base APY) for a vault, bucketed by interval over [from, to].
 */
export const handlersV2GetOpportunityHistoricalHandlerOptions = (
  options: Options<HandlersV2GetOpportunityHistoricalHandlerData>,
) =>
  queryOptions<
    HandlersV2GetOpportunityHistoricalHandlerResponse,
    HandlersV2GetOpportunityHistoricalHandlerError,
    HandlersV2GetOpportunityHistoricalHandlerResponse,
    ReturnType<typeof handlersV2GetOpportunityHistoricalHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetOpportunityHistorical({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetOpportunityHistoricalHandlerQueryKey(options),
  });

export const handlersV2GetOpportunityHistoricalAprHandlerQueryKey = (
  options: Options<HandlersV2GetOpportunityHistoricalAprHandlerData>,
) => createQueryKey("handlersV2GetOpportunityHistoricalAprHandler", options);

/**
 * Get Vault Historical APR
 *
 * Adjacent-pair simple-rate (non-compound) APR per bucket over [from, to]. Reward APR is reserved for future rewards indexing and is always 0.
 */
export const handlersV2GetOpportunityHistoricalAprHandlerOptions = (
  options: Options<HandlersV2GetOpportunityHistoricalAprHandlerData>,
) =>
  queryOptions<
    HandlersV2GetOpportunityHistoricalAprHandlerResponse,
    HandlersV2GetOpportunityHistoricalAprHandlerError,
    HandlersV2GetOpportunityHistoricalAprHandlerResponse,
    ReturnType<typeof handlersV2GetOpportunityHistoricalAprHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetOpportunityHistoricalApr({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetOpportunityHistoricalAprHandlerQueryKey(options),
  });

export const handlersV2GetOpportunityHistoricalApyHandlerQueryKey = (
  options: Options<HandlersV2GetOpportunityHistoricalApyHandlerData>,
) => createQueryKey("handlersV2GetOpportunityHistoricalApyHandler", options);

/**
 * Get Vault Historical APY
 *
 * Adjacent-pair compound APY per bucket over [from, to]. Reward APY is reserved for future rewards indexing and is always 0.
 */
export const handlersV2GetOpportunityHistoricalApyHandlerOptions = (
  options: Options<HandlersV2GetOpportunityHistoricalApyHandlerData>,
) =>
  queryOptions<
    HandlersV2GetOpportunityHistoricalApyHandlerResponse,
    HandlersV2GetOpportunityHistoricalApyHandlerError,
    HandlersV2GetOpportunityHistoricalApyHandlerResponse,
    ReturnType<typeof handlersV2GetOpportunityHistoricalApyHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetOpportunityHistoricalApy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetOpportunityHistoricalApyHandlerQueryKey(options),
  });

export const handlersV2GetOpportunityHistoricalSharePriceHandlerQueryKey = (
  options: Options<HandlersV2GetOpportunityHistoricalSharePriceHandlerData>,
) =>
  createQueryKey(
    "handlersV2GetOpportunityHistoricalSharePriceHandler",
    options,
  );

/**
 * Get Vault Historical Share Price
 *
 * Get historical share-price time-series for a vault, bucketed by interval over [from, to]. Native is denominated in the vault's underlying (base) asset; USD is null when the underlying price is unavailable for the bucket.
 */
export const handlersV2GetOpportunityHistoricalSharePriceHandlerOptions = (
  options: Options<HandlersV2GetOpportunityHistoricalSharePriceHandlerData>,
) =>
  queryOptions<
    HandlersV2GetOpportunityHistoricalSharePriceHandlerResponse,
    HandlersV2GetOpportunityHistoricalSharePriceHandlerError,
    HandlersV2GetOpportunityHistoricalSharePriceHandlerResponse,
    ReturnType<
      typeof handlersV2GetOpportunityHistoricalSharePriceHandlerQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetOpportunityHistoricalSharePrice({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey:
      handlersV2GetOpportunityHistoricalSharePriceHandlerQueryKey(options),
  });

export const handlersV2GetOpportunityHistoricalTvlHandlerQueryKey = (
  options: Options<HandlersV2GetOpportunityHistoricalTvlHandlerData>,
) => createQueryKey("handlersV2GetOpportunityHistoricalTvlHandler", options);

/**
 * Get Vault Historical TVL
 *
 * Get historical TVL time-series for a vault, bucketed by interval over [from, to]. Values are denominated in the vault's underlying (base) asset; USD is null when the underlying price is unavailable for the bucket.
 */
export const handlersV2GetOpportunityHistoricalTvlHandlerOptions = (
  options: Options<HandlersV2GetOpportunityHistoricalTvlHandlerData>,
) =>
  queryOptions<
    HandlersV2GetOpportunityHistoricalTvlHandlerResponse,
    HandlersV2GetOpportunityHistoricalTvlHandlerError,
    HandlersV2GetOpportunityHistoricalTvlHandlerResponse,
    ReturnType<typeof handlersV2GetOpportunityHistoricalTvlHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetOpportunityHistoricalTvl({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetOpportunityHistoricalTvlHandlerQueryKey(options),
  });

export const handlersV2GetProtocolsHandlerQueryKey = (
  options?: Options<HandlersV2GetProtocolsHandlerData>,
) => createQueryKey("handlersV2GetProtocolsHandler", options);

/**
 * Get Supported Protocols
 *
 * Returns supported DeFi protocols with pagination. A protocol is an organization referenced as a lending protocol or vault infra provider in an earn product.
 */
export const handlersV2GetProtocolsHandlerOptions = (
  options?: Options<HandlersV2GetProtocolsHandlerData>,
) =>
  queryOptions<
    HandlersV2GetProtocolsHandlerResponse,
    HandlersV2GetProtocolsHandlerError,
    HandlersV2GetProtocolsHandlerResponse,
    ReturnType<typeof handlersV2GetProtocolsHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetProtocols({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetProtocolsHandlerQueryKey(options),
  });

export const handlersV2GetProtocolsHandlerInfiniteQueryKey = (
  options?: Options<HandlersV2GetProtocolsHandlerData>,
): QueryKey<Options<HandlersV2GetProtocolsHandlerData>> =>
  createQueryKey("handlersV2GetProtocolsHandler", options, true);

/**
 * Get Supported Protocols
 *
 * Returns supported DeFi protocols with pagination. A protocol is an organization referenced as a lending protocol or vault infra provider in an earn product.
 */
export const handlersV2GetProtocolsHandlerInfiniteOptions = (
  options?: Options<HandlersV2GetProtocolsHandlerData>,
) =>
  infiniteQueryOptions<
    HandlersV2GetProtocolsHandlerResponse,
    HandlersV2GetProtocolsHandlerError,
    InfiniteData<HandlersV2GetProtocolsHandlerResponse>,
    QueryKey<Options<HandlersV2GetProtocolsHandlerData>>,
    | number
    | Pick<
        QueryKey<Options<HandlersV2GetProtocolsHandlerData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<HandlersV2GetProtocolsHandlerData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await v2GetProtocols({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: handlersV2GetProtocolsHandlerInfiniteQueryKey(options),
    },
  );

export const handlersV2GetTokensHandlerQueryKey = (
  options?: Options<HandlersV2GetTokensHandlerData>,
) => createQueryKey("handlersV2GetTokensHandler", options);

/**
 * Get Supported Tokens
 *
 * Returns active supported tokens with pagination. Optional filters: chainId (numeric) and search (partial match on address, name or symbol).
 */
export const handlersV2GetTokensHandlerOptions = (
  options?: Options<HandlersV2GetTokensHandlerData>,
) =>
  queryOptions<
    HandlersV2GetTokensHandlerResponse,
    HandlersV2GetTokensHandlerError,
    HandlersV2GetTokensHandlerResponse,
    ReturnType<typeof handlersV2GetTokensHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetTokensHandlerQueryKey(options),
  });

export const handlersV2GetTokensHandlerInfiniteQueryKey = (
  options?: Options<HandlersV2GetTokensHandlerData>,
): QueryKey<Options<HandlersV2GetTokensHandlerData>> =>
  createQueryKey("handlersV2GetTokensHandler", options, true);

/**
 * Get Supported Tokens
 *
 * Returns active supported tokens with pagination. Optional filters: chainId (numeric) and search (partial match on address, name or symbol).
 */
export const handlersV2GetTokensHandlerInfiniteOptions = (
  options?: Options<HandlersV2GetTokensHandlerData>,
) =>
  infiniteQueryOptions<
    HandlersV2GetTokensHandlerResponse,
    HandlersV2GetTokensHandlerError,
    InfiniteData<HandlersV2GetTokensHandlerResponse>,
    QueryKey<Options<HandlersV2GetTokensHandlerData>>,
    | number
    | Pick<
        QueryKey<Options<HandlersV2GetTokensHandlerData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<HandlersV2GetTokensHandlerData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await v2GetTokens({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: handlersV2GetTokensHandlerInfiniteQueryKey(options),
    },
  );

export const handlersV2GetTokenByAddressHandlerQueryKey = (
  options: Options<HandlersV2GetTokenByAddressHandlerData>,
) => createQueryKey("handlersV2GetTokenByAddressHandler", options);

/**
 * Get Token by Chain and Address
 *
 * Returns a single active token identified by its numeric chain ID and contract address.
 */
export const handlersV2GetTokenByAddressHandlerOptions = (
  options: Options<HandlersV2GetTokenByAddressHandlerData>,
) =>
  queryOptions<
    HandlersV2GetTokenByAddressHandlerResponse,
    HandlersV2GetTokenByAddressHandlerError,
    HandlersV2GetTokenByAddressHandlerResponse,
    ReturnType<typeof handlersV2GetTokenByAddressHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v2GetTokenByAddress({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: handlersV2GetTokenByAddressHandlerQueryKey(options),
  });
