// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import type { Options } from "../sdk.gen";
import {
  attributeAction,
  createCancelDepositInteraction,
  createClaimDepositInteraction,
  createDepositInteraction,
  createWithdrawInteraction,
  verifyTracking,
} from "../sdk/actions.gen";
import { getWalletActivity } from "../sdk/activity.gen";
import { getDeposits } from "../sdk/deposits.gen";
import {
  getEarnRoute,
  getEarnSwap,
  getSwapDetails,
  getSwapTokens,
} from "../sdk/earn.gen";
import {
  createMembershipAgreement,
  getMembership,
  membershipCreate,
} from "../sdk/membership.gen";
import {
  getOpportunities,
  getOpportunitiesByDistributor,
  getOpportunityById,
} from "../sdk/opportunities.gen";
import {
  v1StreamsCreatePoint,
  v1StreamsCreateStream,
  v1StreamsGetPoints,
  v1StreamsGetStreams,
  v1StreamsGetTokens,
  v1StreamsGetWallet,
  v1StreamsGetWallets,
} from "../sdk/streams.gen";
import type {
  AttributeActionData,
  AttributeActionError,
  AttributeActionResponse,
  CreateCancelDepositInteractionData,
  CreateCancelDepositInteractionError,
  CreateCancelDepositInteractionResponse,
  CreateClaimDepositInteractionData,
  CreateClaimDepositInteractionError,
  CreateClaimDepositInteractionResponse,
  CreateDepositInteractionData,
  CreateDepositInteractionError,
  CreateDepositInteractionResponse,
  CreateMembershipAgreementData,
  CreateMembershipAgreementError,
  CreateMembershipAgreementResponse,
  CreateWithdrawInteractionData,
  CreateWithdrawInteractionError,
  CreateWithdrawInteractionResponse,
  GetDepositsData,
  GetDepositsError,
  GetDepositsResponse,
  GetEarnRouteData,
  GetEarnRouteError,
  GetEarnRouteResponse,
  GetEarnSwapData,
  GetEarnSwapError,
  GetEarnSwapResponse,
  GetMembershipData,
  GetMembershipResponse,
  GetOpportunitiesByDistributorData,
  GetOpportunitiesByDistributorError,
  GetOpportunitiesByDistributorResponse,
  GetOpportunitiesData,
  GetOpportunitiesError,
  GetOpportunitiesResponse,
  GetOpportunityByIdData,
  GetOpportunityByIdError,
  GetOpportunityByIdResponse,
  GetSwapDetailsData,
  GetSwapDetailsError,
  GetSwapDetailsResponse,
  GetSwapTokensData,
  GetSwapTokensError,
  GetSwapTokensResponse,
  GetWalletActivityData,
  GetWalletActivityError,
  GetWalletActivityResponse,
  MembershipCreateData,
  MembershipCreateError,
  MembershipCreateResponse,
  V1StreamsCreatePointHandlerData,
  V1StreamsCreatePointHandlerError,
  V1StreamsCreatePointHandlerResponse,
  V1StreamsCreateStreamHandlerData,
  V1StreamsCreateStreamHandlerError,
  V1StreamsCreateStreamHandlerResponse,
  V1StreamsGetPointsHandlerData,
  V1StreamsGetPointsHandlerError,
  V1StreamsGetPointsHandlerResponse,
  V1StreamsGetStreamsHandlerData,
  V1StreamsGetStreamsHandlerError,
  V1StreamsGetStreamsHandlerResponse,
  V1StreamsGetTokensHandlerData,
  V1StreamsGetTokensHandlerError,
  V1StreamsGetTokensHandlerResponse,
  V1StreamsGetWalletHandlerData,
  V1StreamsGetWalletHandlerError,
  V1StreamsGetWalletHandlerResponse,
  V1StreamsGetWalletsHandlerData,
  V1StreamsGetWalletsHandlerError,
  V1StreamsGetWalletsHandlerResponse,
  VerifyTrackingData,
  VerifyTrackingError,
  VerifyTrackingResponse,
} from "../types.gen";

/**
 * Attribute Action Handler
 *
 * [DEPRECATED] Attribute a transaction hash to an action. Attribution is now handled automatically by the Lumon collector.
 */
export const attributeActionMutation = (
  options?: Partial<Options<AttributeActionData>>,
): UseMutationOptions<
  AttributeActionResponse,
  AttributeActionError,
  Options<AttributeActionData>
> => {
  const mutationOptions: UseMutationOptions<
    AttributeActionResponse,
    AttributeActionError,
    Options<AttributeActionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await attributeAction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Cancel Deposit Interaction Handler
 *
 * Cancel a pending async deposit.
 */
export const createCancelDepositInteractionMutation = (
  options?: Partial<Options<CreateCancelDepositInteractionData>>,
): UseMutationOptions<
  CreateCancelDepositInteractionResponse,
  CreateCancelDepositInteractionError,
  Options<CreateCancelDepositInteractionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateCancelDepositInteractionResponse,
    CreateCancelDepositInteractionError,
    Options<CreateCancelDepositInteractionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCancelDepositInteraction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Claim Deposit Interaction Handler
 *
 * Claim a pending async deposit. Only requires user wallet address.
 */
export const createClaimDepositInteractionMutation = (
  options?: Partial<Options<CreateClaimDepositInteractionData>>,
): UseMutationOptions<
  CreateClaimDepositInteractionResponse,
  CreateClaimDepositInteractionError,
  Options<CreateClaimDepositInteractionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateClaimDepositInteractionResponse,
    CreateClaimDepositInteractionError,
    Options<CreateClaimDepositInteractionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createClaimDepositInteraction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Interaction Handler
 *
 * Record a deposit interaction
 */
export const createDepositInteractionMutation = (
  options?: Partial<Options<CreateDepositInteractionData>>,
): UseMutationOptions<
  CreateDepositInteractionResponse,
  CreateDepositInteractionError,
  Options<CreateDepositInteractionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateDepositInteractionResponse,
    CreateDepositInteractionError,
    Options<CreateDepositInteractionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createDepositInteraction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const verifyTrackingQueryKey = (options: Options<VerifyTrackingData>) =>
  createQueryKey("verifyTracking", options);

/**
 * Verify Tracking Handler
 *
 * Verify tracking data in a transaction
 */
export const verifyTrackingOptions = (options: Options<VerifyTrackingData>) =>
  queryOptions<
    VerifyTrackingResponse,
    VerifyTrackingError,
    VerifyTrackingResponse,
    ReturnType<typeof verifyTrackingQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await verifyTracking({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: verifyTrackingQueryKey(options),
  });

/**
 * Create Withdraw Interaction Handler
 *
 * Record a withdraw interaction
 */
export const createWithdrawInteractionMutation = (
  options?: Partial<Options<CreateWithdrawInteractionData>>,
): UseMutationOptions<
  CreateWithdrawInteractionResponse,
  CreateWithdrawInteractionError,
  Options<CreateWithdrawInteractionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWithdrawInteractionResponse,
    CreateWithdrawInteractionError,
    Options<CreateWithdrawInteractionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWithdrawInteraction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getDepositsQueryKey = (options: Options<GetDepositsData>) =>
  createQueryKey("getDeposits", options);

/**
 * Get Deposits Handler
 *
 * Get deposit transactions for a specific distributor
 */
export const getDepositsOptions = (options: Options<GetDepositsData>) =>
  queryOptions<
    GetDepositsResponse,
    GetDepositsError,
    GetDepositsResponse,
    ReturnType<typeof getDepositsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDeposits({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDepositsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getDepositsInfiniteQueryKey = (
  options: Options<GetDepositsData>,
): QueryKey<Options<GetDepositsData>> =>
  createQueryKey("getDeposits", options, true);

/**
 * Get Deposits Handler
 *
 * Get deposit transactions for a specific distributor
 */
export const getDepositsInfiniteOptions = (options: Options<GetDepositsData>) =>
  infiniteQueryOptions<
    GetDepositsResponse,
    GetDepositsError,
    InfiniteData<GetDepositsResponse>,
    QueryKey<Options<GetDepositsData>>,
    | null
    | number
    | Pick<
        QueryKey<Options<GetDepositsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetDepositsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getDeposits({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getDepositsInfiniteQueryKey(options),
    },
  );

export const getMembershipQueryKey = (options?: Options<GetMembershipData>) =>
  createQueryKey("getMembership", options);

/**
 * Check Membership
 *
 * Check if a wallet address is associated with a user
 */
export const getMembershipOptions = (options?: Options<GetMembershipData>) =>
  queryOptions<
    GetMembershipResponse,
    DefaultError,
    GetMembershipResponse,
    ReturnType<typeof getMembershipQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMembership({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMembershipQueryKey(options),
  });

/**
 * Create Membership
 *
 * Create a new user and associate wallet (signup only, no session)
 */
export const membershipCreateMutation = (
  options?: Partial<Options<MembershipCreateData>>,
): UseMutationOptions<
  MembershipCreateResponse,
  MembershipCreateError,
  Options<MembershipCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    MembershipCreateResponse,
    MembershipCreateError,
    Options<MembershipCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await membershipCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Membership Agreement
 *
 * Generate a message to be signed by a new wallet for signup
 */
export const createMembershipAgreementMutation = (
  options?: Partial<Options<CreateMembershipAgreementData>>,
): UseMutationOptions<
  CreateMembershipAgreementResponse,
  CreateMembershipAgreementError,
  Options<CreateMembershipAgreementData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMembershipAgreementResponse,
    CreateMembershipAgreementError,
    Options<CreateMembershipAgreementData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMembershipAgreement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOpportunitiesQueryKey = (
  options?: Options<GetOpportunitiesData>,
) => createQueryKey("getOpportunities", options);

/**
 * Get Opportunities Handler
 *
 * Get opportunities with simplified token information
 */
export const getOpportunitiesOptions = (
  options?: Options<GetOpportunitiesData>,
) =>
  queryOptions<
    GetOpportunitiesResponse,
    GetOpportunitiesError,
    GetOpportunitiesResponse,
    ReturnType<typeof getOpportunitiesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOpportunities({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOpportunitiesQueryKey(options),
  });

export const getOpportunitiesByDistributorQueryKey = (
  options: Options<GetOpportunitiesByDistributorData>,
) => createQueryKey("getOpportunitiesByDistributor", options);

/**
 * Get Opportunities By Distributor Handler
 *
 * Get opportunities for a specific distributor based on their earn details configuration
 */
export const getOpportunitiesByDistributorOptions = (
  options: Options<GetOpportunitiesByDistributorData>,
) =>
  queryOptions<
    GetOpportunitiesByDistributorResponse,
    GetOpportunitiesByDistributorError,
    GetOpportunitiesByDistributorResponse,
    ReturnType<typeof getOpportunitiesByDistributorQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOpportunitiesByDistributor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOpportunitiesByDistributorQueryKey(options),
  });

export const getOpportunityByIdQueryKey = (
  options: Options<GetOpportunityByIdData>,
) => createQueryKey("getOpportunityById", options);

/**
 * Get Opportunity By ID Handler
 *
 * Get a single opportunity by ID with simplified token information
 */
export const getOpportunityByIdOptions = (
  options: Options<GetOpportunityByIdData>,
) =>
  queryOptions<
    GetOpportunityByIdResponse,
    GetOpportunityByIdError,
    GetOpportunityByIdResponse,
    ReturnType<typeof getOpportunityByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOpportunityById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOpportunityByIdQueryKey(options),
  });

export const getEarnRouteQueryKey = (options: Options<GetEarnRouteData>) =>
  createQueryKey("getEarnRoute", options);

/**
 * Get Route Handler
 *
 * Get optimal trading route from Enso API for earn widget
 */
export const getEarnRouteOptions = (options: Options<GetEarnRouteData>) =>
  queryOptions<
    GetEarnRouteResponse,
    GetEarnRouteError,
    GetEarnRouteResponse,
    ReturnType<typeof getEarnRouteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEarnRoute({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEarnRouteQueryKey(options),
  });

export const v1StreamsGetStreamsHandlerQueryKey = (
  options?: Options<V1StreamsGetStreamsHandlerData>,
) => createQueryKey("v1StreamsGetStreamsHandler", options);

/**
 * Get Streams Data
 *
 * Get streams for the organization associated with the API key, optionally filtered by stream ID and with optional snapshots.
 */
export const v1StreamsGetStreamsHandlerOptions = (
  options?: Options<V1StreamsGetStreamsHandlerData>,
) =>
  queryOptions<
    V1StreamsGetStreamsHandlerResponse,
    V1StreamsGetStreamsHandlerError,
    V1StreamsGetStreamsHandlerResponse,
    ReturnType<typeof v1StreamsGetStreamsHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1StreamsGetStreams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1StreamsGetStreamsHandlerQueryKey(options),
  });

/**
 * Create Stream with API Key Authentication
 *
 * Handle create stream and signature request
 */
export const v1StreamsCreateStreamHandlerMutation = (
  options?: Partial<Options<V1StreamsCreateStreamHandlerData>>,
): UseMutationOptions<
  V1StreamsCreateStreamHandlerResponse,
  V1StreamsCreateStreamHandlerError,
  Options<V1StreamsCreateStreamHandlerData>
> => {
  const mutationOptions: UseMutationOptions<
    V1StreamsCreateStreamHandlerResponse,
    V1StreamsCreateStreamHandlerError,
    Options<V1StreamsCreateStreamHandlerData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1StreamsCreateStream({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1StreamsGetPointsHandlerQueryKey = (
  options?: Options<V1StreamsGetPointsHandlerData>,
) => createQueryKey("v1StreamsGetPointsHandler", options);

/**
 * Get Stream Points
 *
 * Get the points that belong to the organization associated with the API key.
 */
export const v1StreamsGetPointsHandlerOptions = (
  options?: Options<V1StreamsGetPointsHandlerData>,
) =>
  queryOptions<
    V1StreamsGetPointsHandlerResponse,
    V1StreamsGetPointsHandlerError,
    V1StreamsGetPointsHandlerResponse,
    ReturnType<typeof v1StreamsGetPointsHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1StreamsGetPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1StreamsGetPointsHandlerQueryKey(options),
  });

/**
 * Create Stream Point
 *
 * Create a point for the organization associated with the API key.
 */
export const v1StreamsCreatePointHandlerMutation = (
  options?: Partial<Options<V1StreamsCreatePointHandlerData>>,
): UseMutationOptions<
  V1StreamsCreatePointHandlerResponse,
  V1StreamsCreatePointHandlerError,
  Options<V1StreamsCreatePointHandlerData>
> => {
  const mutationOptions: UseMutationOptions<
    V1StreamsCreatePointHandlerResponse,
    V1StreamsCreatePointHandlerError,
    Options<V1StreamsCreatePointHandlerData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await v1StreamsCreatePoint({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const v1StreamsGetTokensHandlerQueryKey = (
  options: Options<V1StreamsGetTokensHandlerData>,
) => createQueryKey("v1StreamsGetTokensHandler", options);

/**
 * Get Stream Tokens
 *
 * Get all supported tokens for a chain that can be used for streams.
 */
export const v1StreamsGetTokensHandlerOptions = (
  options: Options<V1StreamsGetTokensHandlerData>,
) =>
  queryOptions<
    V1StreamsGetTokensHandlerResponse,
    V1StreamsGetTokensHandlerError,
    V1StreamsGetTokensHandlerResponse,
    ReturnType<typeof v1StreamsGetTokensHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1StreamsGetTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1StreamsGetTokensHandlerQueryKey(options),
  });

export const v1StreamsGetWalletsHandlerQueryKey = (
  options: Options<V1StreamsGetWalletsHandlerData>,
) => createQueryKey("v1StreamsGetWalletsHandler", options);

/**
 * Get Stream Wallets
 *
 * Retrieve the wallets participating in a stream along with their latest snapshot data.
 *
 * **Pagination:**
 * - Use 'page' (default: 1) and 'limit' (default: 20) query parameters.
 * - Results are ordered by rewardsAccumulated descending.
 *
 * **Note:**
 * - rewardsAccumulated and rewardsAccumulatedBase are represented in wei units.
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWalletsHandlerOptions = (
  options: Options<V1StreamsGetWalletsHandlerData>,
) =>
  queryOptions<
    V1StreamsGetWalletsHandlerResponse,
    V1StreamsGetWalletsHandlerError,
    V1StreamsGetWalletsHandlerResponse,
    ReturnType<typeof v1StreamsGetWalletsHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1StreamsGetWallets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1StreamsGetWalletsHandlerQueryKey(options),
  });

export const v1StreamsGetWalletsHandlerInfiniteQueryKey = (
  options: Options<V1StreamsGetWalletsHandlerData>,
): QueryKey<Options<V1StreamsGetWalletsHandlerData>> =>
  createQueryKey("v1StreamsGetWalletsHandler", options, true);

/**
 * Get Stream Wallets
 *
 * Retrieve the wallets participating in a stream along with their latest snapshot data.
 *
 * **Pagination:**
 * - Use 'page' (default: 1) and 'limit' (default: 20) query parameters.
 * - Results are ordered by rewardsAccumulated descending.
 *
 * **Note:**
 * - rewardsAccumulated and rewardsAccumulatedBase are represented in wei units.
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWalletsHandlerInfiniteOptions = (
  options: Options<V1StreamsGetWalletsHandlerData>,
) =>
  infiniteQueryOptions<
    V1StreamsGetWalletsHandlerResponse,
    V1StreamsGetWalletsHandlerError,
    InfiniteData<V1StreamsGetWalletsHandlerResponse>,
    QueryKey<Options<V1StreamsGetWalletsHandlerData>>,
    | number
    | Pick<
        QueryKey<Options<V1StreamsGetWalletsHandlerData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<V1StreamsGetWalletsHandlerData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await v1StreamsGetWallets({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: v1StreamsGetWalletsHandlerInfiniteQueryKey(options),
    },
  );

export const v1StreamsGetWalletHandlerQueryKey = (
  options: Options<V1StreamsGetWalletHandlerData>,
) => createQueryKey("v1StreamsGetWalletHandler", options);

/**
 * Get Stream Wallet Data
 *
 * Retrieve all reward snapshots accumulated by a wallet for a specific stream.
 *
 * **Note:**
 * - The following fields are represented in wei units:
 * - wallet.snapshots[].rewardsAccumulated
 * - wallet.stream.totalAmount
 * - wallet.stream.lastSnapshot.amountDistributed
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWalletHandlerOptions = (
  options: Options<V1StreamsGetWalletHandlerData>,
) =>
  queryOptions<
    V1StreamsGetWalletHandlerResponse,
    V1StreamsGetWalletHandlerError,
    V1StreamsGetWalletHandlerResponse,
    ReturnType<typeof v1StreamsGetWalletHandlerQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await v1StreamsGetWallet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: v1StreamsGetWalletHandlerQueryKey(options),
  });

export const getEarnSwapQueryKey = (options: Options<GetEarnSwapData>) =>
  createQueryKey("getEarnSwap", options);

/**
 * Get Swap Handler
 *
 * Build approve + swap transactions via the router for an arbitrary token pair
 */
export const getEarnSwapOptions = (options: Options<GetEarnSwapData>) =>
  queryOptions<
    GetEarnSwapResponse,
    GetEarnSwapError,
    GetEarnSwapResponse,
    ReturnType<typeof getEarnSwapQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEarnSwap({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEarnSwapQueryKey(options),
  });

export const getSwapDetailsQueryKey = (options?: Options<GetSwapDetailsData>) =>
  createQueryKey("getSwapDetails", options);

/**
 * Get Swap Details Handler
 *
 * Static-ish swap picker data: supported chains plus popular tokens for the selected chain
 */
export const getSwapDetailsOptions = (options?: Options<GetSwapDetailsData>) =>
  queryOptions<
    GetSwapDetailsResponse,
    GetSwapDetailsError,
    GetSwapDetailsResponse,
    ReturnType<typeof getSwapDetailsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSwapDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSwapDetailsQueryKey(options),
  });

export const getSwapTokensQueryKey = (options: Options<GetSwapTokensData>) =>
  createQueryKey("getSwapTokens", options);

/**
 * Get Swap Tokens Handler
 *
 * Search swap tokens for a chain. Partial match on symbol/name/address against the curated catalog, with an Enso fallback (by address or exact symbol) when the catalog has no result
 */
export const getSwapTokensOptions = (options: Options<GetSwapTokensData>) =>
  queryOptions<
    GetSwapTokensResponse,
    GetSwapTokensError,
    GetSwapTokensResponse,
    ReturnType<typeof getSwapTokensQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSwapTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSwapTokensQueryKey(options),
  });

export const getSwapTokensInfiniteQueryKey = (
  options: Options<GetSwapTokensData>,
): QueryKey<Options<GetSwapTokensData>> =>
  createQueryKey("getSwapTokens", options, true);

/**
 * Get Swap Tokens Handler
 *
 * Search swap tokens for a chain. Partial match on symbol/name/address against the curated catalog, with an Enso fallback (by address or exact symbol) when the catalog has no result
 */
export const getSwapTokensInfiniteOptions = (
  options: Options<GetSwapTokensData>,
) =>
  infiniteQueryOptions<
    GetSwapTokensResponse,
    GetSwapTokensError,
    InfiniteData<GetSwapTokensResponse>,
    QueryKey<Options<GetSwapTokensData>>,
    | number
    | Pick<
        QueryKey<Options<GetSwapTokensData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetSwapTokensData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getSwapTokens({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getSwapTokensInfiniteQueryKey(options),
    },
  );

export const getWalletActivityQueryKey = (
  options?: Options<GetWalletActivityData>,
) => createQueryKey("getWalletActivity", options);

/**
 * Get Wallet Activity Handler
 *
 * Get paginated verified earn interactions for the given wallet addresses (comma-separated), ordered by date descending.
 */
export const getWalletActivityOptions = (
  options?: Options<GetWalletActivityData>,
) =>
  queryOptions<
    GetWalletActivityResponse,
    GetWalletActivityError,
    GetWalletActivityResponse,
    ReturnType<typeof getWalletActivityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWalletActivity({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWalletActivityQueryKey(options),
  });

export const getWalletActivityInfiniteQueryKey = (
  options?: Options<GetWalletActivityData>,
): QueryKey<Options<GetWalletActivityData>> =>
  createQueryKey("getWalletActivity", options, true);

/**
 * Get Wallet Activity Handler
 *
 * Get paginated verified earn interactions for the given wallet addresses (comma-separated), ordered by date descending.
 */
export const getWalletActivityInfiniteOptions = (
  options?: Options<GetWalletActivityData>,
) =>
  infiniteQueryOptions<
    GetWalletActivityResponse,
    GetWalletActivityError,
    InfiniteData<GetWalletActivityResponse>,
    QueryKey<Options<GetWalletActivityData>>,
    | number
    | Pick<
        QueryKey<Options<GetWalletActivityData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWalletActivityData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWalletActivity({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getWalletActivityInfiniteQueryKey(options),
    },
  );
