// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AttributeActionData,
  AttributeActionErrors,
  AttributeActionResponses,
  CreateCancelDepositInteractionData,
  CreateCancelDepositInteractionErrors,
  CreateCancelDepositInteractionResponses,
  CreateClaimDepositInteractionData,
  CreateClaimDepositInteractionErrors,
  CreateClaimDepositInteractionResponses,
  CreateDepositInteractionData,
  CreateDepositInteractionErrors,
  CreateDepositInteractionResponses,
  CreateMembershipAgreementData,
  CreateMembershipAgreementErrors,
  CreateMembershipAgreementResponses,
  CreateWithdrawInteractionData,
  CreateWithdrawInteractionErrors,
  CreateWithdrawInteractionResponses,
  GetDepositsData,
  GetDepositsErrors,
  GetDepositsResponses,
  GetEarnRouteData,
  GetEarnRouteErrors,
  GetEarnRouteResponses,
  GetEarnSwapData,
  GetEarnSwapErrors,
  GetEarnSwapResponses,
  GetMembershipData,
  GetMembershipResponses,
  GetOpportunitiesByDistributorData,
  GetOpportunitiesByDistributorErrors,
  GetOpportunitiesByDistributorResponses,
  GetOpportunitiesData,
  GetOpportunitiesErrors,
  GetOpportunitiesResponses,
  GetOpportunityByIdData,
  GetOpportunityByIdErrors,
  GetOpportunityByIdResponses,
  GetSwapDetailsData,
  GetSwapDetailsErrors,
  GetSwapDetailsResponses,
  GetSwapTokensData,
  GetSwapTokensErrors,
  GetSwapTokensResponses,
  GetWalletActivityData,
  GetWalletActivityErrors,
  GetWalletActivityResponses,
  MembershipCreateData,
  MembershipCreateErrors,
  MembershipCreateResponses,
  V1StreamsCreatePointHandlerData,
  V1StreamsCreatePointHandlerErrors,
  V1StreamsCreatePointHandlerResponses,
  V1StreamsCreateStreamHandlerData,
  V1StreamsCreateStreamHandlerErrors,
  V1StreamsCreateStreamHandlerResponses,
  V1StreamsGetPointsHandlerData,
  V1StreamsGetPointsHandlerErrors,
  V1StreamsGetPointsHandlerResponses,
  V1StreamsGetStreamsHandlerData,
  V1StreamsGetStreamsHandlerErrors,
  V1StreamsGetStreamsHandlerResponses,
  V1StreamsGetTokensHandlerData,
  V1StreamsGetTokensHandlerErrors,
  V1StreamsGetTokensHandlerResponses,
  V1StreamsGetWalletHandlerData,
  V1StreamsGetWalletHandlerErrors,
  V1StreamsGetWalletHandlerResponses,
  V1StreamsGetWalletsHandlerData,
  V1StreamsGetWalletsHandlerErrors,
  V1StreamsGetWalletsHandlerResponses,
  VerifyTrackingData,
  VerifyTrackingErrors,
  VerifyTrackingResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Attribute Action Handler
 *
 * [DEPRECATED] Attribute a transaction hash to an action. Attribution is now handled automatically by the Lumon collector.
 */
export const attributeAction = <ThrowOnError extends boolean = false>(
  options: Options<AttributeActionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AttributeActionResponses,
    AttributeActionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/attribute/{actionId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Cancel Deposit Interaction Handler
 *
 * Cancel a pending async deposit.
 */
export const createCancelDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCancelDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCancelDepositInteractionResponses,
    CreateCancelDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/cancel-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Claim Deposit Interaction Handler
 *
 * Claim a pending async deposit. Only requires user wallet address.
 */
export const createClaimDepositInteraction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateClaimDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateClaimDepositInteractionResponses,
    CreateClaimDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/claim-deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Interaction Handler
 *
 * Record a deposit interaction
 */
export const createDepositInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateDepositInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDepositInteractionResponses,
    CreateDepositInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/deposit/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify Tracking Handler
 *
 * Verify tracking data in a transaction
 */
export const verifyTracking = <ThrowOnError extends boolean = false>(
  options: Options<VerifyTrackingData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    VerifyTrackingResponses,
    VerifyTrackingErrors,
    ThrowOnError
  >({ url: "/v1/actions/verify", ...options });

/**
 * Create Withdraw Interaction Handler
 *
 * Record a withdraw interaction
 */
export const createWithdrawInteraction = <ThrowOnError extends boolean = false>(
  options: Options<CreateWithdrawInteractionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateWithdrawInteractionResponses,
    CreateWithdrawInteractionErrors,
    ThrowOnError
  >({
    url: "/v1/actions/withdraw/{opportunityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Deposits Handler
 *
 * Get deposit transactions for a specific distributor
 */
export const getDeposits = <ThrowOnError extends boolean = false>(
  options: Options<GetDepositsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDepositsResponses,
    GetDepositsErrors,
    ThrowOnError
  >({ url: "/v1/deposit/{distributor_id}", ...options });

/**
 * Check Membership
 *
 * Check if a wallet address is associated with a user
 */
export const getMembership = <ThrowOnError extends boolean = false>(
  options?: Options<GetMembershipData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMembershipResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/membership/", ...options });

/**
 * Create Membership
 *
 * Create a new user and associate wallet (signup only, no session)
 */
export const membershipCreate = <ThrowOnError extends boolean = false>(
  options?: Options<MembershipCreateData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    MembershipCreateResponses,
    MembershipCreateErrors,
    ThrowOnError
  >({
    url: "/v1/membership/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Create Membership Agreement
 *
 * Generate a message to be signed by a new wallet for signup
 */
export const createMembershipAgreement = <ThrowOnError extends boolean = false>(
  options?: Options<CreateMembershipAgreementData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateMembershipAgreementResponses,
    CreateMembershipAgreementErrors,
    ThrowOnError
  >({
    url: "/v1/membership/agreement",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get Opportunities Handler
 *
 * Get opportunities with simplified token information
 */
export const getOpportunities = <ThrowOnError extends boolean = false>(
  options?: Options<GetOpportunitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetOpportunitiesResponses,
    GetOpportunitiesErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/", ...options });

/**
 * Get Opportunities By Distributor Handler
 *
 * Get opportunities for a specific distributor based on their earn details configuration
 */
export const getOpportunitiesByDistributor = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOpportunitiesByDistributorData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunitiesByDistributorResponses,
    GetOpportunitiesByDistributorErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/distributors/{distributor_id}", ...options });

/**
 * Get Opportunity By ID Handler
 *
 * Get a single opportunity by ID with simplified token information
 */
export const getOpportunityById = <ThrowOnError extends boolean = false>(
  options: Options<GetOpportunityByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOpportunityByIdResponses,
    GetOpportunityByIdErrors,
    ThrowOnError
  >({ url: "/v1/opportunities/{id}", ...options });

/**
 * Get Route Handler
 *
 * Get optimal trading route from Enso API for earn widget
 */
export const getEarnRoute = <ThrowOnError extends boolean = false>(
  options: Options<GetEarnRouteData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEarnRouteResponses,
    GetEarnRouteErrors,
    ThrowOnError
  >({ url: "/v1/route/", ...options });

/**
 * Get Streams Data
 *
 * Get streams for the organization associated with the API key, optionally filtered by stream ID and with optional snapshots.
 */
export const v1StreamsGetStreamsHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<V1StreamsGetStreamsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    V1StreamsGetStreamsHandlerResponses,
    V1StreamsGetStreamsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/", ...options });

/**
 * Create Stream with API Key Authentication
 *
 * Handle create stream and signature request
 */
export const v1StreamsCreateStreamHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<V1StreamsCreateStreamHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    V1StreamsCreateStreamHandlerResponses,
    V1StreamsCreateStreamHandlerErrors,
    ThrowOnError
  >({
    url: "/v1/streams/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get Stream Points
 *
 * Get the points that belong to the organization associated with the API key.
 */
export const v1StreamsGetPointsHandler = <ThrowOnError extends boolean = false>(
  options?: Options<V1StreamsGetPointsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    V1StreamsGetPointsHandlerResponses,
    V1StreamsGetPointsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/points", ...options });

/**
 * Create Stream Point
 *
 * Create a point for the organization associated with the API key.
 */
export const v1StreamsCreatePointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<V1StreamsCreatePointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    V1StreamsCreatePointHandlerResponses,
    V1StreamsCreatePointHandlerErrors,
    ThrowOnError
  >({
    url: "/v1/streams/points",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get Stream Tokens
 *
 * Get all supported tokens for a chain that can be used for streams.
 */
export const v1StreamsGetTokensHandler = <ThrowOnError extends boolean = false>(
  options: Options<V1StreamsGetTokensHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetTokensHandlerResponses,
    V1StreamsGetTokensHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/tokens", ...options });

/**
 * Get Stream Wallets
 *
 * Retrieve the wallets participating in a stream along with their latest snapshot data.
 *
 * **Pagination:**
 * - Use 'page' (default: 1) and 'limit' (default: 20) query parameters.
 * - Results are ordered by rewardsAccumulated descending.
 *
 * **Note:**
 * - rewardsAccumulated and rewardsAccumulatedBase are represented in wei units.
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWalletsHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<V1StreamsGetWalletsHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetWalletsHandlerResponses,
    V1StreamsGetWalletsHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/{id}/wallets", ...options });

/**
 * Get Stream Wallet Data
 *
 * Retrieve all reward snapshots accumulated by a wallet for a specific stream.
 *
 * **Note:**
 * - The following fields are represented in wei units:
 * - wallet.snapshots[].rewardsAccumulated
 * - wallet.stream.totalAmount
 * - wallet.stream.lastSnapshot.amountDistributed
 * - The stream must belong to the organization associated with the API key.
 */
export const v1StreamsGetWalletHandler = <ThrowOnError extends boolean = false>(
  options: Options<V1StreamsGetWalletHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    V1StreamsGetWalletHandlerResponses,
    V1StreamsGetWalletHandlerErrors,
    ThrowOnError
  >({ url: "/v1/streams/{id}/wallets/{address}", ...options });

/**
 * Get Swap Handler
 *
 * Build approve + swap transactions via the router for an arbitrary token pair
 */
export const getEarnSwap = <ThrowOnError extends boolean = false>(
  options: Options<GetEarnSwapData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEarnSwapResponses,
    GetEarnSwapErrors,
    ThrowOnError
  >({ url: "/v1/swap/", ...options });

/**
 * Get Swap Details Handler
 *
 * Static-ish swap picker data: supported chains plus popular tokens for the selected chain
 */
export const getSwapDetails = <ThrowOnError extends boolean = false>(
  options?: Options<GetSwapDetailsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSwapDetailsResponses,
    GetSwapDetailsErrors,
    ThrowOnError
  >({ url: "/v1/swap/details", ...options });

/**
 * Get Swap Tokens Handler
 *
 * Search swap tokens for a chain. Partial match on symbol/name/address against the curated catalog, with an Enso fallback (by address or exact symbol) when the catalog has no result
 */
export const getSwapTokens = <ThrowOnError extends boolean = false>(
  options: Options<GetSwapTokensData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSwapTokensResponses,
    GetSwapTokensErrors,
    ThrowOnError
  >({ url: "/v1/swap/tokens", ...options });

/**
 * Get Wallet Activity Handler
 *
 * Get paginated verified earn interactions for the given wallet addresses (comma-separated), ordered by date descending.
 */
export const getWalletActivity = <ThrowOnError extends boolean = false>(
  options?: Options<GetWalletActivityData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetWalletActivityResponses,
    GetWalletActivityErrors,
    ThrowOnError
  >({ url: "/v1/wallets/activity/", ...options });
