// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zUuidUuid = z.uuid().nullable();

export const zV1ChainResponse = z.object({
  chainId: z.string().optional(),
  ecosystem: z.string().optional(),
  explorerUrl: z.string().optional(),
  id: zUuidUuid.optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  status: z.string().optional(),
});

export const zV1TokenResponse = z.object({
  address: z.string().optional(),
  chain: zV1ChainResponse.optional(),
  decimals: z.int().optional(),
  id: zUuidUuid.optional(),
  isNative: z.boolean().optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  symbol: z.string().optional(),
});

export const zV1SwapToken = z.object({
  address: z.string().optional(),
  chainId: z.string().optional(),
  decimals: z.int().optional(),
  isNative: z.boolean().optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  priceUsd: z.number().optional(),
  symbol: z.string().optional(),
});

export const zV1SwapChain = z.object({
  chainId: z.string().optional(),
  ecosystem: z.string().optional(),
  explorerUrl: z.string().optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  nativePriceUsd: z.number().optional(),
  slug: z.string().optional(),
});

export const zV1IncentiveResponse = z.object({
  apr: z.number().nullish(),
  description: z.string().optional(),
  estPriceUsd: z.number().nullish(),
  fdvEstimate: z.number().nullish(),
  iconUrl: z.string().optional(),
  id: zUuidUuid.optional(),
  indexed: z.boolean().optional(),
  maxApr: z.number().nullish(),
  minApr: z.number().nullish(),
  name: z.string().optional(),
  rewardType: z.string().optional(),
  rewardTypeName: z.string().optional(),
  status: z.string().optional(),
  tokenSupplyAllocation: z.number().nullish(),
});

export const zUtilsPaginationResponse = z.object({
  hasNext: z.boolean().nullish(),
  hasPrevious: z.boolean().nullish(),
  limit: z.int().optional(),
  page: z.int().optional(),
  total: z.int().optional(),
  totalPages: z.int().optional(),
});

export const zV1GetSwapTokensResponse = z.object({
  data: z.array(zV1SwapToken).nullish(),
  pagination: zUtilsPaginationResponse.optional(),
});

export const zTypesTransaction = z.object({
  chainId: z.int().optional(),
  data: z.string().optional(),
  gasLimit: z.string().optional(),
  to: z.string().optional(),
  value: z.string().optional(),
});

export const zTypesTokenDetails = z.object({
  address: z.string().optional(),
  decimals: z.int().optional(),
  logoUrl: z.string().optional(),
  symbol: z.string().optional(),
});

export const zTypesRouteStep = z.object({
  action: z.string().optional(),
  from: zTypesTokenDetails.optional(),
  to: zTypesTokenDetails.optional(),
});

export const zTypesSwapMetadata = z.object({
  amountOut: z.string().optional(),
  gas: z.string().optional(),
  provider: z.string().optional(),
  providerImg: z.string().optional(),
  route: z.array(zTypesRouteStep).nullish(),
});

export const zTypesTxResponseItem = z.object({
  description: z.string().optional(),
  metadata: zTypesSwapMetadata.optional(),
  transaction: zTypesTransaction.optional(),
  type: z.string().optional(),
});

export const zV1GetSwapResponse = z.object({
  actionId: zUuidUuid.optional(),
  transactions: z.array(zTypesTxResponseItem).nullish(),
});

export const zV1GetSwapDetailsResponse = z.object({
  chains: z.array(zV1SwapChain).nullish(),
  popularTokens: z.array(zV1SwapToken).nullish(),
});

export const zV1CuratorResponse = z.object({
  description: z.string().optional(),
  iconUrl: z.string().optional(),
  landingUrl: z.string().optional(),
  name: z.string().optional(),
});

export const zV1EarnOpportunityResponse = z.object({
  baseTokens: zV1TokenResponse.optional(),
  curator: zV1CuratorResponse.optional(),
  depositTokens: z.array(zV1TokenResponse).nullish(),
  description: z.string().optional(),
  estimatedApr: z.number().optional(),
  featured: z.boolean().optional(),
  id: zUuidUuid.optional(),
  incentives: z.array(zV1IncentiveResponse).nullish(),
  minDepositAmountUsd: z.number().optional(),
  name: z.string().optional(),
  receiptToken: zV1TokenResponse.optional(),
  swapDirectEnabled: z.boolean().optional(),
  swapRouteEnabled: z.boolean().optional(),
  tvl: z.number().optional(),
  type: z.string().optional(),
});

export const zV1GetOpportunityByIdResponse = z.object({
  opportunity: zV1EarnOpportunityResponse.optional(),
});

export const zV1GetOpportunitiesResponse = z.object({
  opportunities: z.array(zV1EarnOpportunityResponse).nullish(),
  total: z.int().optional(),
});

export const zV1GetMembershipOutput = z.object({
  isMember: z.boolean().optional(),
});

export const zV1CreateMembershipOutput = z.object({
  error: z.string().optional(),
  isMember: z.boolean().optional(),
});

export const zV1CreateMembershipInput = z.object({
  address: z.string(),
  distributor_id: z.string().optional(),
  nonce: z.string(),
  signature: z.string(),
  walletEcosystem: z.string(),
});

export const zV1CreateMembershipAgreementOutput = z.object({
  message: z.string().optional(),
  nonce: z.string().optional(),
});

export const zV1CreateMembershipAgreementInput = z.object({
  address: z.string(),
  chainId: z.string().optional().default("1"),
  url: z.string(),
  walletEcosystem: z.enum(["evm", "solana", "ton"]),
});

export const zTrackingEarnTrackingMetadata = z.object({
  action: z.string().optional(),
  actionId: z.string().optional(),
  amount: z.string().optional(),
  amountUsd: z.string().optional(),
  distributorId: z.string().optional(),
  opportunityId: z.string().optional(),
  referralCode: z.string().optional(),
  tokenIn: z.string().optional(),
  tokenInDecimals: z.int().optional(),
});

export const zStreamsWalletSnapshot = z.object({
  apr: z.string().nullish(),
  baseApr: z.string().nullish(),
  baseTvl: z.string().nullish(),
  createdAt: z.iso.datetime().optional(),
  customMetrics: z.unknown().optional(),
  netTvl: z.string().nullish(),
  rewardsAccumulated: z.string().optional(),
  rewardsAccumulatedBase: z.string().optional(),
  timestamp: z.iso.datetime().optional(),
  turtleNetTvl: z.string().nullish(),
  turtleTvl: z.string().nullish(),
  tvl: z.string().nullish(),
  updatedAt: z.iso.datetime().optional(),
});

export const zStreamsWalletWithLastSnapshot = z.object({
  lastSnapshot: zStreamsWalletSnapshot.optional(),
  userAddress: z.string().optional(),
});

export const zStreamsSupportedToken = z.object({
  address: z.string().optional(),
  chainId: z.int().gte(0).optional(),
  decimals: z.int().optional(),
  id: zUuidUuid.optional(),
  isAllowedRewardToken: z.boolean().optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  symbol: z.string().optional(),
});

export const zStreamsPoint = z.object({
  createdAt: z.iso.datetime().optional(),
  decimals: z.int().gte(0).optional(),
  id: zUuidUuid.optional(),
  logoUrl: z.string().nullish(),
  name: z.string().optional(),
  orgId: zUuidUuid.optional(),
  symbol: z.string().optional(),
  updatedAt: z.iso.datetime().optional(),
});

export const zStreamsStreamSnapshot = z.object({
  activeUserCount: z.int().gte(0).nullish(),
  amountBase: z.string().nullish(),
  amountDistributed: z.string().nullish(),
  apr: z.string().nullish(),
  baseApr: z.string().nullish(),
  baseTvl: z.string().nullish(),
  commitTxHash: z.string().nullish(),
  createdAt: z.iso.datetime().optional(),
  customArgs: z.unknown().optional(),
  customMetrics: z.unknown().optional(),
  netTvl: z.string().nullish(),
  rewardTokenPrice: z.string().nullish(),
  rootHash: z.string().nullish(),
  timestamp: z.iso.datetime().optional(),
  turtleNetTvl: z.string().nullish(),
  turtleTvl: z.string().nullish(),
  tvl: z.string().nullish(),
  updatedAt: z.iso.datetime().optional(),
  userCount: z.int().gte(0).nullish(),
});

export const zStreamsAdapterConfig = z.object({
  params: z.unknown().optional(),
  type: z.string().optional(),
});

export const zStreamsAdapterConfigs = z.array(zStreamsAdapterConfig).nullable();

export const zStreamsStream = z.object({
  adapters: zStreamsAdapterConfigs.optional(),
  admin: z.string().nullish(),
  chainId: z.int().gte(0).nullish(),
  claimPaused: z.boolean().optional(),
  committedSnapshot: zStreamsStreamSnapshot.optional(),
  contractAddress: z.string().nullish(),
  createdAt: z.iso.datetime().optional(),
  creationConfirmedAt: z.iso.datetime().nullish(),
  customArgs: z.unknown().optional(),
  endTimestamp: z.iso.datetime().nullish(),
  hashCommitmentPaused: z.boolean().optional(),
  id: zUuidUuid.optional(),
  lastSnapshot: zStreamsStreamSnapshot.optional(),
  merkleTreeComputationPaused: z.boolean().optional(),
  orgId: zUuidUuid.optional(),
  point: zStreamsPoint.optional(),
  rewardToken: zStreamsSupportedToken.optional(),
  snapshotComputationPaused: z.boolean().optional(),
  snapshots: z.array(zStreamsStreamSnapshot).optional(),
  startTimestamp: z.iso.datetime().optional(),
  strategy: z.string().optional(),
  totalAmount: z.string().nullish(),
  type: z.int().gte(0).optional(),
  updatedAt: z.iso.datetime().optional(),
  userId: zUuidUuid.optional(),
});

export const zStreamsWalletData = z.object({
  snapshots: z.array(zStreamsWalletSnapshot).nullish(),
  stream: zStreamsStream.optional(),
  streamId: zUuidUuid.optional(),
  userAddress: z.string().nullish(),
});

export const zStreamsIStreamFactoryCreateStreamParams = z.record(
  z.string(),
  z.unknown(),
);

export const zStreamsGetWalletsOutput = z.object({
  data: z.array(zStreamsWalletWithLastSnapshot).nullish(),
  pagination: zUtilsPaginationResponse.optional(),
});

export const zStreamsGetWalletOutput = z.object({
  wallet: zStreamsWalletData.optional(),
});

export const zStreamsGetTokensOutput = z.object({
  tokens: z.array(zStreamsSupportedToken).nullish(),
});

export const zStreamsGetStreamsOutput = z.object({
  streams: z.array(zStreamsStream).nullish(),
});

export const zStreamsGetPointsOutput = z.object({
  points: z.array(zStreamsPoint).nullish(),
});

export const zStreamsCreateStreamFuncParams = z.object({
  deadline: z.string().nullish(),
  params: zStreamsIStreamFactoryCreateStreamParams.optional(),
  signature: z.string().optional(),
});

export const zStreamsCreateStreamTxParams = z.object({
  chainId: z.int().gte(0).optional(),
  params: zStreamsCreateStreamFuncParams.optional(),
  sender: z.string().nullish(),
});

export const zStreamsAdapterConfigType2 = z.object({
  params: z.unknown().optional(),
  type: z.string().optional(),
});

export const zStreamsAdapterConfigsType2 = z
  .array(zStreamsAdapterConfigType2)
  .nullable();

export const zStreamsCreateStreamRequestParams = z.object({
  adapters: zStreamsAdapterConfigsType2.optional(),
  customArgs: z.unknown().optional(),
  endTimestamp: z.iso.datetime().nullish(),
  pointId: zUuidUuid.optional(),
  rewardTokenId: zUuidUuid.optional(),
  startTimestamp: z.iso.datetime().optional(),
  totalAmount: z.string().nullish(),
  type: z.int().gte(0).optional(),
  walletAddress: z.string().nullish(),
});

export const zStreamsCreateStreamOutput = z.object({
  message: z.string().optional(),
  stream: zStreamsStream.optional(),
  txParams: zStreamsCreateStreamTxParams.optional(),
});

export const zStreamsCreatePointOutput = z.object({
  point: zStreamsPoint.optional(),
});

export const zStreamsCreatePointInput = z.object({
  decimals: z.int().gte(0).nullish(),
  logoUrl: z.string().nullish(),
  name: z.string().optional(),
  symbol: z.string().optional(),
});

export const zRestErrResponse = z.object({
  code: z.int().optional(),
  context: z.record(z.string(), z.unknown()).optional(),
  error: z.string().optional(),
  status: z.string().optional(),
});

export const zActionsWithdrawRequest = z.object({
  amount: z.string(),
  distributorId: z.string(),
  slippageBps: z.int().optional(),
  tokenOut: z.string().optional(),
  userAddress: z.string(),
});

export const zActionsWalletActivityItem = z.object({
  amountInUsd: z.string().nullish(),
  amountToken: z.string().nullish(),
  blockTimestamp: z.string().nullish(),
  chainId: z.int().optional(),
  id: zUuidUuid.optional(),
  interaction: z.string().optional(),
  isSwap: z.boolean().optional(),
  opportunityId: zUuidUuid.optional(),
  tokenIconUrl: z.string().nullish(),
  tokenSymbol: z.string().nullish(),
  txHash: z.string().optional(),
  walletAddress: z.string().optional(),
});

export const zActionsWalletActivityResponse = z.object({
  activity: z.array(zActionsWalletActivityItem).nullish(),
  pagination: zUtilsPaginationResponse.optional(),
});

export const zActionsVerifyTrackingResponse = z.object({
  error: z.string().optional(),
  metadata: zTrackingEarnTrackingMetadata.optional(),
  signatureValid: z.boolean().optional(),
  tag: z.string().optional(),
});

export const zActionsInteractionResponse = z.object({
  actionId: zUuidUuid.optional(),
  transactions: z.array(zTypesTxResponseItem).nullish(),
});

export const zActionsInteractionRequest = z.object({
  amount: z.string(),
  distributorId: z.string(),
  mode: z.string().optional().default("direct"),
  referralCode: z.string().optional(),
  slippageBps: z.int().optional().default(50),
  tokenIn: z.string(),
  userAddress: z.string(),
});

export const zActionsDistributorDepositsResponse = z.object({
  deposits: z.array(zActionsWalletActivityItem).nullish(),
  pagination: zUtilsPaginationResponse.optional(),
});

export const zActionsClaimDepositRequest = z.object({
  distributorId: z.string(),
  userAddress: z.string(),
});

export const zActionsCancelDepositRequest = z.object({
  distributorId: z.string(),
  userAddress: z.string(),
});

export const zActionsAttributeActionResponse = z.object({
  deprecated: z.boolean().optional(),
  message: z.string().optional(),
  signatureValid: z.boolean().optional(),
  success: z.boolean().optional(),
});

export const zActionsAttributeActionRequest = z.object({
  txHash: z.string(),
});

export const zAttributeActionBody = zActionsAttributeActionRequest;

export const zAttributeActionPath = z.object({
  actionId: zUuidUuid,
});

/**
 * OK
 */
export const zAttributeActionResponse = zActionsAttributeActionResponse;

export const zCreateCancelDepositInteractionBody = zActionsCancelDepositRequest;

export const zCreateCancelDepositInteractionPath = z.object({
  opportunityId: zUuidUuid,
});

/**
 * OK
 */
export const zCreateCancelDepositInteractionResponse =
  zActionsInteractionResponse;

export const zCreateClaimDepositInteractionBody = zActionsClaimDepositRequest;

export const zCreateClaimDepositInteractionPath = z.object({
  opportunityId: zUuidUuid,
});

/**
 * OK
 */
export const zCreateClaimDepositInteractionResponse =
  zActionsInteractionResponse;

export const zCreateDepositInteractionBody = zActionsInteractionRequest;

export const zCreateDepositInteractionPath = z.object({
  opportunityId: zUuidUuid,
});

/**
 * OK
 */
export const zCreateDepositInteractionResponse = zActionsInteractionResponse;

export const zVerifyTrackingQuery = z.object({
  chainId: z.int(),
  txHash: z.string(),
});

/**
 * OK
 */
export const zVerifyTrackingResponse = zActionsVerifyTrackingResponse;

export const zCreateWithdrawInteractionBody = zActionsWithdrawRequest;

export const zCreateWithdrawInteractionPath = z.object({
  opportunityId: zUuidUuid,
});

/**
 * OK
 */
export const zCreateWithdrawInteractionResponse = zActionsInteractionResponse;

export const zGetDistributorDepositsPath = z.object({
  distributor_id: z.string(),
});

export const zGetDistributorDepositsQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
  opportunity_id: z.string().optional(),
  product_id: z.string().optional(),
});

/**
 * OK
 */
export const zGetDistributorDepositsResponse =
  zActionsDistributorDepositsResponse;

export const zGetMembershipQuery = z.object({
  address: z.string().optional(),
  walletEcosystem: z.enum(["evm", "solana", "ton"]).optional().default("evm"),
});

/**
 * OK
 */
export const zGetMembershipResponse = zV1GetMembershipOutput;

export const zMembershipCreateBody = zV1CreateMembershipInput;

/**
 * OK
 */
export const zMembershipCreateResponse = zV1CreateMembershipOutput;

export const zCreateMembershipAgreementBody = zV1CreateMembershipAgreementInput;

/**
 * OK
 */
export const zCreateMembershipAgreementResponse =
  zV1CreateMembershipAgreementOutput;

export const zGetOpportunitiesQuery = z.object({
  chainIds: z.string().optional(),
  depositToken: z.string().optional(),
  tvlGreaterThan: z.number().optional(),
});

/**
 * OK
 */
export const zGetOpportunitiesResponse = zV1GetOpportunitiesResponse;

export const zGetOpportunitiesByDistributorPath = z.object({
  distributor_id: z.string(),
});

/**
 * OK
 */
export const zGetOpportunitiesByDistributorResponse =
  zV1GetOpportunitiesResponse;

export const zGetOpportunityByIdPath = z.object({
  id: zUuidUuid,
});

/**
 * OK
 */
export const zGetOpportunityByIdResponse = zV1GetOpportunityByIdResponse;

export const zV1StreamsGetStreamsHandlerQuery = z.object({
  id: zUuidUuid.optional(),
  withSnapshots: z.boolean().optional(),
  usersCount: z.boolean().optional(),
});

/**
 * OK
 */
export const zV1StreamsGetStreamsHandlerResponse = zStreamsGetStreamsOutput;

export const zV1StreamsCreateStreamHandlerBody =
  zStreamsCreateStreamRequestParams;

/**
 * OK
 */
export const zV1StreamsCreateStreamHandlerResponse = zStreamsCreateStreamOutput;

export const zV1StreamsGetPointsHandlerQuery = z.object({
  id: zUuidUuid.optional(),
  symbol: z.string().optional(),
  name: z.string().optional(),
});

/**
 * OK
 */
export const zV1StreamsGetPointsHandlerResponse = zStreamsGetPointsOutput;

export const zV1StreamsCreatePointHandlerBody = zStreamsCreatePointInput;

/**
 * OK
 */
export const zV1StreamsCreatePointHandlerResponse = zStreamsCreatePointOutput;

export const zV1StreamsGetTokensHandlerQuery = z.object({
  chainId: z.int().gte(0),
});

/**
 * OK
 */
export const zV1StreamsGetTokensHandlerResponse = zStreamsGetTokensOutput;

export const zV1StreamsGetWalletsHandlerPath = z.object({
  id: zUuidUuid,
});

export const zV1StreamsGetWalletsHandlerQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
});

/**
 * OK
 */
export const zV1StreamsGetWalletsHandlerResponse = zStreamsGetWalletsOutput;

export const zV1StreamsGetWalletHandlerPath = z.object({
  id: zUuidUuid,
  address: z.string(),
});

/**
 * OK
 */
export const zV1StreamsGetWalletHandlerResponse = zStreamsGetWalletOutput;

export const zGetEarnSwapQuery = z.object({
  user: z.string(),
  chain: z.int().gte(1),
  distributor_id: z.string(),
  token_in: z.string(),
  token_out: z.string(),
  amount_in: z.string(),
  slippage_bps: z.int().gte(1).lte(5000),
});

/**
 * OK
 */
export const zGetEarnSwapResponse = zV1GetSwapResponse;

export const zGetSwapDetailsQuery = z.object({
  chainId: z.int().optional(),
});

/**
 * OK
 */
export const zGetSwapDetailsResponse = zV1GetSwapDetailsResponse;

export const zGetSwapTokensQuery = z.object({
  chainId: z.int().gte(1),
  search: z.string().optional(),
  page: z.int().optional(),
  limit: z.int().optional(),
});

/**
 * OK
 */
export const zGetSwapTokensResponse = zV1GetSwapTokensResponse;

export const zGetWalletActivityQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
  addresses: z.string().optional(),
});

/**
 * OK
 */
export const zGetWalletActivityResponse = zActionsWalletActivityResponse;
