// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  HandlersV2GetChainsHandlerData,
  HandlersV2GetChainsHandlerErrors,
  HandlersV2GetChainsHandlerResponses,
  HandlersV2GetOpportunityHistoricalAprHandlerData,
  HandlersV2GetOpportunityHistoricalAprHandlerErrors,
  HandlersV2GetOpportunityHistoricalAprHandlerResponses,
  HandlersV2GetOpportunityHistoricalApyHandlerData,
  HandlersV2GetOpportunityHistoricalApyHandlerErrors,
  HandlersV2GetOpportunityHistoricalApyHandlerResponses,
  HandlersV2GetOpportunityHistoricalHandlerData,
  HandlersV2GetOpportunityHistoricalHandlerErrors,
  HandlersV2GetOpportunityHistoricalHandlerResponses,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerData,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors,
  HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses,
  HandlersV2GetOpportunityHistoricalTvlHandlerData,
  HandlersV2GetOpportunityHistoricalTvlHandlerErrors,
  HandlersV2GetOpportunityHistoricalTvlHandlerResponses,
  HandlersV2GetProtocolsHandlerData,
  HandlersV2GetProtocolsHandlerErrors,
  HandlersV2GetProtocolsHandlerResponses,
  HandlersV2GetTokenByAddressHandlerData,
  HandlersV2GetTokenByAddressHandlerErrors,
  HandlersV2GetTokenByAddressHandlerResponses,
  HandlersV2GetTokensHandlerData,
  HandlersV2GetTokensHandlerErrors,
  HandlersV2GetTokensHandlerResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Supported Chains
 *
 * Returns all supported chains with pagination. Chains are filtered to active status only.
 */
export const v2GetChains = <ThrowOnError extends boolean = false>(
  options?: Options<HandlersV2GetChainsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HandlersV2GetChainsHandlerResponses,
    HandlersV2GetChainsHandlerErrors,
    ThrowOnError
  >({ url: "/v2/chains/", ...options });

/**
 * Get Vault Historical Data
 *
 * Get combined historical time-series (TVL, share price, base APY) for a vault, bucketed by interval over [from, to].
 */
export const v2GetOpportunityHistorical = <
  ThrowOnError extends boolean = false,
>(
  options: Options<HandlersV2GetOpportunityHistoricalHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    HandlersV2GetOpportunityHistoricalHandlerResponses,
    HandlersV2GetOpportunityHistoricalHandlerErrors,
    ThrowOnError
  >({
    url: "/v2/opportunities/{chainId}/{vaultAddress}/historical",
    ...options,
  });

/**
 * Get Vault Historical APR
 *
 * Adjacent-pair simple-rate (non-compound) APR per bucket over [from, to]. Reward APR is reserved for future rewards indexing and is always 0.
 */
export const v2GetOpportunityHistoricalApr = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HandlersV2GetOpportunityHistoricalAprHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    HandlersV2GetOpportunityHistoricalAprHandlerResponses,
    HandlersV2GetOpportunityHistoricalAprHandlerErrors,
    ThrowOnError
  >({
    url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apr",
    ...options,
  });

/**
 * Get Vault Historical APY
 *
 * Adjacent-pair compound APY per bucket over [from, to]. Reward APY is reserved for future rewards indexing and is always 0.
 */
export const v2GetOpportunityHistoricalApy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HandlersV2GetOpportunityHistoricalApyHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    HandlersV2GetOpportunityHistoricalApyHandlerResponses,
    HandlersV2GetOpportunityHistoricalApyHandlerErrors,
    ThrowOnError
  >({
    url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apy",
    ...options,
  });

/**
 * Get Vault Historical Share Price
 *
 * Get historical share-price time-series for a vault, bucketed by interval over [from, to]. Native is denominated in the vault's underlying (base) asset; USD is null when the underlying price is unavailable for the bucket.
 */
export const v2GetOpportunityHistoricalSharePrice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HandlersV2GetOpportunityHistoricalSharePriceHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses,
    HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors,
    ThrowOnError
  >({
    url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/share-price",
    ...options,
  });

/**
 * Get Vault Historical TVL
 *
 * Get historical TVL time-series for a vault, bucketed by interval over [from, to]. Values are denominated in the vault's underlying (base) asset; USD is null when the underlying price is unavailable for the bucket.
 */
export const v2GetOpportunityHistoricalTvl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HandlersV2GetOpportunityHistoricalTvlHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    HandlersV2GetOpportunityHistoricalTvlHandlerResponses,
    HandlersV2GetOpportunityHistoricalTvlHandlerErrors,
    ThrowOnError
  >({
    url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/tvl",
    ...options,
  });

/**
 * Get Supported Protocols
 *
 * Returns supported DeFi protocols with pagination. A protocol is an organization referenced as a lending protocol or vault infra provider in an earn product.
 */
export const v2GetProtocols = <ThrowOnError extends boolean = false>(
  options?: Options<HandlersV2GetProtocolsHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HandlersV2GetProtocolsHandlerResponses,
    HandlersV2GetProtocolsHandlerErrors,
    ThrowOnError
  >({ url: "/v2/protocols/", ...options });

/**
 * Get Supported Tokens
 *
 * Returns active supported tokens with pagination. Optional filters: chainId (numeric) and search (partial match on address, name or symbol).
 */
export const v2GetTokens = <ThrowOnError extends boolean = false>(
  options?: Options<HandlersV2GetTokensHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HandlersV2GetTokensHandlerResponses,
    HandlersV2GetTokensHandlerErrors,
    ThrowOnError
  >({ url: "/v2/tokens/", ...options });

/**
 * Get Token by Chain and Address
 *
 * Returns a single active token identified by its numeric chain ID and contract address.
 */
export const v2GetTokenByAddress = <ThrowOnError extends boolean = false>(
  options: Options<HandlersV2GetTokenByAddressHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    HandlersV2GetTokenByAddressHandlerResponses,
    HandlersV2GetTokenByAddressHandlerErrors,
    ThrowOnError
  >({ url: "/v2/tokens/{chainId}/{address}", ...options });
