// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://earn.turtle.xyz" | (string & {});
};

export type V2ProtocolResponse = {
  /**
   * Protocol logo image URL
   */
  logoUrl?: string;
  /**
   * Protocol name
   */
  name?: string;
  /**
   * Protocol website URL
   */
  siteUrl?: string;
};

export type V2NativeUsdValue = {
  native?: number;
  /**
   * null when underlying USD price was not available for this bucket
   */
  usd?: null | number;
};

export type V2HistoricalTvlPoint = {
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
  tvl?: V2NativeUsdValue;
};

export type V2HistoricalSharePricePoint = {
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  sharePrice?: V2NativeUsdValue;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2HistoricalCombinedPoint = {
  /**
   * Trailing-window APY at this bucket; null when no predecessor exists
   */
  apy?: V2ApyBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  sharePrice?: V2NativeUsdValue;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
  tvl?: V2NativeUsdValue;
};

export type V2ApyBreakdown = {
  /**
   * APY from share-price growth alone (vaults.fyi compound formula)
   */
  base?: number;
  /**
   * Reward APY; reserved for future rewards indexing, currently always 0
   */
  reward?: number;
  /**
   * base + reward
   */
  total?: number;
} | null;

export type V2HistoricalApyPoint = {
  /**
   * Adjacent-pair compound APY against the previous bucket
   */
  apy?: V2ApyBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2HistoricalAprPoint = {
  /**
   * Adjacent-pair simple-rate APR against the previous bucket
   */
  apr?: V2AprBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2AprBreakdown = {
  /**
   * APR from share-price growth alone (simple, non-compound)
   */
  base?: number;
  /**
   * Reward APR; reserved for future rewards indexing, currently always 0
   */
  reward?: number;
  /**
   * base + reward
   */
  total?: number;
};

export type V2GetOpportunityHistoricalTvlResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalTvlPoint> | null;
};

export type SharedTokenResponse = {
  /**
   * Token contract address
   */
  address?: string;
  /**
   * Numeric chain ID the token belongs to
   */
  chainId?: number;
  /**
   * ERC20 decimals
   */
  decimals?: number;
  /**
   * Token logo image URL
   */
  logoUrl?: string;
  /**
   * Token symbol (e.g. USDC, ETH)
   */
  symbol?: string;
};

export type V2GetOpportunityHistoricalSharePriceResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalSharePricePoint> | null;
};

export type V2GetOpportunityHistoricalResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalCombinedPoint> | null;
  /**
   * true when backend hit the row cap and oldest APY values may be missing predecessors
   */
  historyTruncated?: boolean;
};

export type V2GetOpportunityHistoricalApyResponse = {
  data?: Array<V2HistoricalApyPoint> | null;
};

export type V2GetOpportunityHistoricalAprResponse = {
  data?: Array<V2HistoricalAprPoint> | null;
};

export type SharedChainResponse = {
  /**
   * Numeric chain ID (e.g. 1 for Ethereum, 43114 for Avalanche)
   */
  chainId?: number;
  /**
   * Block explorer base URL
   */
  explorerUrl?: string;
  /**
   * Chain logo image URL
   */
  logoUrl?: string;
  /**
   * Chain full name
   */
  name?: string;
};

export type RestErrResponse = {
  /**
   * Application-specific error code.
   */
  code?: number;
  /**
   * Application context.
   */
  context?: {
    [key: string]: unknown;
  };
  /**
   * Error message.
   */
  error?: string;
  /**
   * Status text.
   */
  status?: string;
};

export type PaginationPaginationMetadata = {
  limit?: number;
  page?: number;
  total?: number;
  totalPages?: number;
};

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse =
  {
    data?: Array<SharedTokenResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse =
  {
    data?: Array<SharedChainResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse =
  {
    data?: Array<V2ProtocolResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type HandlersV2GetChainsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/v2/chains/";
};

export type HandlersV2GetChainsHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetChainsHandlerError =
  HandlersV2GetChainsHandlerErrors[keyof HandlersV2GetChainsHandlerErrors];

export type HandlersV2GetChainsHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse;
};

export type HandlersV2GetChainsHandlerResponse =
  HandlersV2GetChainsHandlerResponses[keyof HandlersV2GetChainsHandlerResponses];

export type HandlersV2GetOpportunityHistoricalHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical";
};

export type HandlersV2GetOpportunityHistoricalHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalHandlerError =
  HandlersV2GetOpportunityHistoricalHandlerErrors[keyof HandlersV2GetOpportunityHistoricalHandlerErrors];

export type HandlersV2GetOpportunityHistoricalHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalResponse;
};

export type HandlersV2GetOpportunityHistoricalHandlerResponse =
  HandlersV2GetOpportunityHistoricalHandlerResponses[keyof HandlersV2GetOpportunityHistoricalHandlerResponses];

export type HandlersV2GetOpportunityHistoricalAprHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apr";
};

export type HandlersV2GetOpportunityHistoricalAprHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalAprHandlerError =
  HandlersV2GetOpportunityHistoricalAprHandlerErrors[keyof HandlersV2GetOpportunityHistoricalAprHandlerErrors];

export type HandlersV2GetOpportunityHistoricalAprHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalAprResponse;
};

export type HandlersV2GetOpportunityHistoricalAprHandlerResponse =
  HandlersV2GetOpportunityHistoricalAprHandlerResponses[keyof HandlersV2GetOpportunityHistoricalAprHandlerResponses];

export type HandlersV2GetOpportunityHistoricalApyHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apy";
};

export type HandlersV2GetOpportunityHistoricalApyHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalApyHandlerError =
  HandlersV2GetOpportunityHistoricalApyHandlerErrors[keyof HandlersV2GetOpportunityHistoricalApyHandlerErrors];

export type HandlersV2GetOpportunityHistoricalApyHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalApyResponse;
};

export type HandlersV2GetOpportunityHistoricalApyHandlerResponse =
  HandlersV2GetOpportunityHistoricalApyHandlerResponses[keyof HandlersV2GetOpportunityHistoricalApyHandlerResponses];

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/share-price";
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerError =
  HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors[keyof HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors];

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalSharePriceResponse;
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerResponse =
  HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses[keyof HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses];

export type HandlersV2GetOpportunityHistoricalTvlHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/tvl";
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerError =
  HandlersV2GetOpportunityHistoricalTvlHandlerErrors[keyof HandlersV2GetOpportunityHistoricalTvlHandlerErrors];

export type HandlersV2GetOpportunityHistoricalTvlHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalTvlResponse;
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerResponse =
  HandlersV2GetOpportunityHistoricalTvlHandlerResponses[keyof HandlersV2GetOpportunityHistoricalTvlHandlerResponses];

export type HandlersV2GetProtocolsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/v2/protocols/";
};

export type HandlersV2GetProtocolsHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetProtocolsHandlerError =
  HandlersV2GetProtocolsHandlerErrors[keyof HandlersV2GetProtocolsHandlerErrors];

export type HandlersV2GetProtocolsHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse;
};

export type HandlersV2GetProtocolsHandlerResponse =
  HandlersV2GetProtocolsHandlerResponses[keyof HandlersV2GetProtocolsHandlerResponses];

export type HandlersV2GetTokensHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    /**
     * Filter by numeric chain ID
     */
    chainId?: number;
    /**
     * Case-insensitive partial match across address, name and symbol
     */
    search?: string;
  };
  url: "/v2/tokens/";
};

export type HandlersV2GetTokensHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetTokensHandlerError =
  HandlersV2GetTokensHandlerErrors[keyof HandlersV2GetTokensHandlerErrors];

export type HandlersV2GetTokensHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse;
};

export type HandlersV2GetTokensHandlerResponse =
  HandlersV2GetTokensHandlerResponses[keyof HandlersV2GetTokensHandlerResponses];

export type HandlersV2GetTokenByAddressHandlerData = {
  body?: never;
  path: {
    /**
     * Numeric chain ID
     */
    chainId: number;
    /**
     * Token contract address (case-insensitive)
     */
    address: string;
  };
  query?: never;
  url: "/v2/tokens/{chainId}/{address}";
};

export type HandlersV2GetTokenByAddressHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetTokenByAddressHandlerError =
  HandlersV2GetTokenByAddressHandlerErrors[keyof HandlersV2GetTokenByAddressHandlerErrors];

export type HandlersV2GetTokenByAddressHandlerResponses = {
  /**
   * OK
   */
  200: SharedTokenResponse;
};

export type HandlersV2GetTokenByAddressHandlerResponse =
  HandlersV2GetTokenByAddressHandlerResponses[keyof HandlersV2GetTokenByAddressHandlerResponses];
