// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zV2ProtocolResponse = z.object({
  logoUrl: z.string().optional(),
  name: z.string().optional(),
  siteUrl: z.string().optional(),
});

export const zV2NativeUsdValue = z.object({
  native: z.number().optional(),
  usd: z.number().nullish(),
});

export const zV2HistoricalTvlPoint = z.object({
  blockNumber: z.int().gte(0).optional(),
  timestamp: z.int().optional(),
  tvl: zV2NativeUsdValue.optional(),
});

export const zV2HistoricalSharePricePoint = z.object({
  blockNumber: z.int().gte(0).optional(),
  sharePrice: zV2NativeUsdValue.optional(),
  timestamp: z.int().optional(),
});

export const zV2ApyBreakdown = z
  .object({
    base: z.number().optional(),
    reward: z.number().optional(),
    total: z.number().optional(),
  })
  .nullable();

export const zV2HistoricalCombinedPoint = z.object({
  apy: zV2ApyBreakdown.optional(),
  blockNumber: z.int().gte(0).optional(),
  sharePrice: zV2NativeUsdValue.optional(),
  timestamp: z.int().optional(),
  tvl: zV2NativeUsdValue.optional(),
});

export const zV2HistoricalApyPoint = z.object({
  apy: zV2ApyBreakdown.optional(),
  blockNumber: z.int().gte(0).optional(),
  timestamp: z.int().optional(),
});

export const zV2AprBreakdown = z.object({
  base: z.number().optional(),
  reward: z.number().optional(),
  total: z.number().optional(),
});

export const zV2HistoricalAprPoint = z.object({
  apr: zV2AprBreakdown.optional(),
  blockNumber: z.int().gte(0).optional(),
  timestamp: z.int().optional(),
});

export const zSharedTokenResponse = z.object({
  address: z.string().optional(),
  chainId: z.int().optional(),
  decimals: z.int().optional(),
  logoUrl: z.string().optional(),
  symbol: z.string().optional(),
});

export const zV2GetOpportunityHistoricalTvlResponse = z.object({
  baseAsset: zSharedTokenResponse.optional(),
  data: z.array(zV2HistoricalTvlPoint).nullish(),
});

export const zV2GetOpportunityHistoricalSharePriceResponse = z.object({
  baseAsset: zSharedTokenResponse.optional(),
  data: z.array(zV2HistoricalSharePricePoint).nullish(),
});

export const zV2GetOpportunityHistoricalResponse = z.object({
  baseAsset: zSharedTokenResponse.optional(),
  data: z.array(zV2HistoricalCombinedPoint).nullish(),
  historyTruncated: z.boolean().optional(),
});

export const zV2GetOpportunityHistoricalApyResponse = z.object({
  data: z.array(zV2HistoricalApyPoint).nullish(),
});

export const zV2GetOpportunityHistoricalAprResponse = z.object({
  data: z.array(zV2HistoricalAprPoint).nullish(),
});

export const zSharedChainResponse = z.object({
  chainId: z.int().optional(),
  explorerUrl: z.string().optional(),
  logoUrl: z.string().optional(),
  name: z.string().optional(),
});

export const zRestErrResponse = z.object({
  code: z.int().optional(),
  context: z.record(z.string(), z.unknown()).optional(),
  error: z.string().optional(),
  status: z.string().optional(),
});

export const zPaginationPaginationMetadata = z.object({
  limit: z.int().optional(),
  page: z.int().optional(),
  total: z.int().optional(),
  totalPages: z.int().optional(),
});

export const zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse =
  z.object({
    data: z.array(zSharedTokenResponse).nullish(),
    pagination: zPaginationPaginationMetadata.optional(),
  });

export const zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse =
  z.object({
    data: z.array(zSharedChainResponse).nullish(),
    pagination: zPaginationPaginationMetadata.optional(),
  });

export const zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse =
  z.object({
    data: z.array(zV2ProtocolResponse).nullish(),
    pagination: zPaginationPaginationMetadata.optional(),
  });

export const zHandlersV2GetChainsHandlerQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetChainsHandlerResponse =
  zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse;

export const zHandlersV2GetOpportunityHistoricalHandlerPath = z.object({
  chainId: z.int().gte(1),
  vaultAddress: z.string(),
});

export const zHandlersV2GetOpportunityHistoricalHandlerQuery = z.object({
  intervalSeconds: z.int().gte(1).optional().default(86400),
  fromTimestamp: z.int().optional(),
  toTimestamp: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetOpportunityHistoricalHandlerResponse =
  zV2GetOpportunityHistoricalResponse;

export const zHandlersV2GetOpportunityHistoricalAprHandlerPath = z.object({
  chainId: z.int().gte(1),
  vaultAddress: z.string(),
});

export const zHandlersV2GetOpportunityHistoricalAprHandlerQuery = z.object({
  intervalSeconds: z.int().gte(1).optional().default(86400),
  fromTimestamp: z.int().optional(),
  toTimestamp: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetOpportunityHistoricalAprHandlerResponse =
  zV2GetOpportunityHistoricalAprResponse;

export const zHandlersV2GetOpportunityHistoricalApyHandlerPath = z.object({
  chainId: z.int().gte(1),
  vaultAddress: z.string(),
});

export const zHandlersV2GetOpportunityHistoricalApyHandlerQuery = z.object({
  intervalSeconds: z.int().gte(1).optional().default(86400),
  fromTimestamp: z.int().optional(),
  toTimestamp: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetOpportunityHistoricalApyHandlerResponse =
  zV2GetOpportunityHistoricalApyResponse;

export const zHandlersV2GetOpportunityHistoricalSharePriceHandlerPath =
  z.object({
    chainId: z.int().gte(1),
    vaultAddress: z.string(),
  });

export const zHandlersV2GetOpportunityHistoricalSharePriceHandlerQuery =
  z.object({
    intervalSeconds: z.int().gte(1).optional().default(86400),
    fromTimestamp: z.int().optional(),
    toTimestamp: z.int().optional(),
  });

/**
 * OK
 */
export const zHandlersV2GetOpportunityHistoricalSharePriceHandlerResponse =
  zV2GetOpportunityHistoricalSharePriceResponse;

export const zHandlersV2GetOpportunityHistoricalTvlHandlerPath = z.object({
  chainId: z.int().gte(1),
  vaultAddress: z.string(),
});

export const zHandlersV2GetOpportunityHistoricalTvlHandlerQuery = z.object({
  intervalSeconds: z.int().gte(1).optional().default(86400),
  fromTimestamp: z.int().optional(),
  toTimestamp: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetOpportunityHistoricalTvlHandlerResponse =
  zV2GetOpportunityHistoricalTvlResponse;

export const zHandlersV2GetProtocolsHandlerQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetProtocolsHandlerResponse =
  zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse;

export const zHandlersV2GetTokensHandlerQuery = z.object({
  page: z.int().optional(),
  limit: z.int().optional(),
  chainId: z.int().optional(),
  search: z.string().optional(),
});

/**
 * OK
 */
export const zHandlersV2GetTokensHandlerResponse =
  zPaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse;

export const zHandlersV2GetTokenByAddressHandlerPath = z.object({
  chainId: z.int(),
  address: z.string(),
});

/**
 * OK
 */
export const zHandlersV2GetTokenByAddressHandlerResponse = zSharedTokenResponse;
