// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://earn.turtle.xyz" | (string & {});
};

export type ActionsAttributeActionRequest = {
  /**
   * Transaction hash to attribute to the action
   */
  txHash: string;
};

export type ActionsAttributeActionResponse = {
  /**
   * This endpoint is deprecated. Attribution is now automatic.
   */
  deprecated?: boolean;
  /**
   * Response message
   */
  message?: string;
  /**
   * Whether the tracking signature was valid
   */
  signatureValid?: boolean;
  /**
   * Whether the operation was successful
   */
  success?: boolean;
};

export type ActionsCancelDepositRequest = {
  /**
   * Distributor ID
   */
  distributorId: string;
  /**
   * User wallet address
   */
  userAddress: string;
};

export type ActionsClaimDepositRequest = {
  /**
   * Distributor ID
   */
  distributorId: string;
  /**
   * User wallet address
   */
  userAddress: string;
};

export type ActionsInteractionRequest = {
  /**
   * Amount in smallest unit (wei)
   */
  amount: string;
  /**
   * Distributor ID
   */
  distributorId: string;
  /**
   * Mode: 'swap' to use router, 'direct' for direct deposit
   */
  mode?: string;
  /**
   * Optional referral code
   */
  referralCode?: string;
  /**
   * Slippage tolerance in basis points (e.g., 50 = 0.5%)
   */
  slippageBps?: number;
  /**
   * Input token address
   */
  tokenIn: string;
  /**
   * User wallet address (validated by middleware)
   */
  userAddress: string;
};

export type ActionsInteractionResponse = {
  /**
   * Unique identifier for the saved interaction
   */
  actionId?: UuidUuid;
  /**
   * Ordered list of transactions to execute
   */
  transactions?: Array<TypesTxResponseItem> | null;
};

export type ActionsVerifyTrackingResponse = {
  /**
   * Error message if verification failed
   */
  error?: string;
  /**
   * The parsed tracking metadata
   */
  metadata?: TrackingEarnTrackingMetadata;
  /**
   * Whether the signature is from our attribution wallet
   */
  signatureValid?: boolean;
  /**
   * The tracking tag found in the transaction
   */
  tag?: string;
};

export type ActionsWalletActivityItem = {
  amountInUsd?: null | string;
  amountToken?: null | string;
  blockTimestamp?: null | string;
  chainId?: number;
  id?: UuidUuid;
  interaction?: string;
  isSwap?: boolean;
  opportunityId?: UuidUuid;
  tokenIconUrl?: null | string;
  tokenSymbol?: null | string;
  txHash?: string;
  walletAddress?: string;
};

export type ActionsWalletActivityResponse = {
  activity?: Array<ActionsWalletActivityItem> | null;
  pagination?: UtilsPaginationResponse;
};

export type ActionsWithdrawRequest = {
  /**
   * Shares to redeem in smallest unit
   */
  amount: string;
  /**
   * Distributor ID
   */
  distributorId: string;
  /**
   * Optional: slippage tolerance in basis points (e.g., 50 = 0.5%). Only applied to opportunities that require it
   */
  slippageBps?: number;
  /**
   * Optional: token to receive after withdrawal (required for Midas, Mellow, Veda)
   */
  tokenOut?: string;
  /**
   * User wallet address (validated by middleware)
   */
  userAddress: string;
};

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse =
  {
    data?: Array<V2ProtocolResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse =
  {
    data?: Array<SharedChainResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse =
  {
    data?: Array<SharedTokenResponse> | null;
    pagination?: PaginationPaginationMetadata;
  };

export type PaginationPaginationMetadata = {
  limit?: number;
  page?: number;
  total?: number;
  totalPages?: number;
};

export type RestErrResponse = {
  /**
   * Application-specific error code.
   */
  code?: number;
  /**
   * Application context.
   */
  context?: {
    [key: string]: unknown;
  };
  /**
   * Error message.
   */
  error?: string;
  /**
   * Status text.
   */
  status?: string;
};

export type SharedChainResponse = {
  /**
   * Numeric chain ID (e.g. 1 for Ethereum, 43114 for Avalanche)
   */
  chainId?: number;
  /**
   * Block explorer base URL
   */
  explorerUrl?: string;
  /**
   * Chain logo image URL
   */
  logoUrl?: string;
  /**
   * Chain full name
   */
  name?: string;
};

export type SharedTokenResponse = {
  /**
   * Token contract address
   */
  address?: string;
  /**
   * Numeric chain ID the token belongs to
   */
  chainId?: number;
  /**
   * ERC20 decimals
   */
  decimals?: number;
  /**
   * Token logo image URL
   */
  logoUrl?: string;
  /**
   * Token symbol (e.g. USDC, ETH)
   */
  symbol?: string;
};

export type StreamsAdapterConfig = {
  params?: unknown;
  type?: string;
};

export type StreamsAdapterConfigType2 = {
  params?: unknown;
  type?: string;
};

export type StreamsAdapterConfigs = Array<StreamsAdapterConfig> | null;

export type StreamsAdapterConfigsType2 =
  Array<StreamsAdapterConfigType2> | null;

export type StreamsCreatePointInput = {
  decimals?: null | number;
  logoUrl?: null | string;
  name?: string;
  symbol?: string;
};

export type StreamsCreatePointOutput = {
  point?: StreamsPoint;
};

export type StreamsCreateStreamFuncParams = {
  deadline?: null | string;
  params?: StreamsIStreamFactoryCreateStreamParams;
  signature?: string;
};

export type StreamsCreateStreamOutput = {
  message?: string;
  stream?: StreamsStream;
  txParams?: StreamsCreateStreamTxParams;
};

export type StreamsCreateStreamRequestParams = {
  adapters?: StreamsAdapterConfigsType2;
  customArgs?: unknown;
  endTimestamp?: null | string;
  pointId?: UuidUuid;
  rewardTokenId?: UuidUuid;
  startTimestamp?: string;
  totalAmount?: null | string;
  type?: number;
  walletAddress?: string | null;
};

export type StreamsCreateStreamTxParams = {
  chainId?: number;
  params?: StreamsCreateStreamFuncParams;
  sender?: string | null;
};

export type StreamsGetPointsOutput = {
  points?: Array<StreamsPoint> | null;
};

export type StreamsGetStreamsOutput = {
  streams?: Array<StreamsStream> | null;
};

export type StreamsGetTokensOutput = {
  tokens?: Array<StreamsSupportedToken> | null;
};

export type StreamsGetWalletOutput = {
  wallet?: StreamsWalletData;
};

export type StreamsGetWalletsOutput = {
  data?: Array<StreamsWalletWithLastSnapshot> | null;
  pagination?: UtilsPaginationResponse;
};

export type StreamsIStreamFactoryCreateStreamParams = {
  [key: string]: unknown;
};

export type StreamsPoint = {
  createdAt?: string;
  decimals?: number;
  id?: UuidUuid;
  logoUrl?: null | string;
  name?: string;
  orgId?: UuidUuid;
  symbol?: string;
  updatedAt?: string;
};

export type StreamsStream = {
  adapters?: StreamsAdapterConfigs;
  admin?: string | null;
  chainId?: null | number;
  claimPaused?: boolean;
  committedSnapshot?: StreamsStreamSnapshot;
  contractAddress?: string | null;
  createdAt?: string;
  creationConfirmedAt?: null | string;
  customArgs?: unknown;
  endTimestamp?: null | string;
  hashCommitmentPaused?: boolean;
  id?: UuidUuid;
  lastSnapshot?: StreamsStreamSnapshot;
  merkleTreeComputationPaused?: boolean;
  orgId?: UuidUuid;
  point?: StreamsPoint;
  rewardToken?: StreamsSupportedToken;
  snapshotComputationPaused?: boolean;
  snapshots?: Array<StreamsStreamSnapshot>;
  startTimestamp?: string;
  strategy?: string;
  totalAmount?: null | string;
  type?: number;
  updatedAt?: string;
  userId?: UuidUuid;
};

export type StreamsStreamSnapshot = {
  activeUserCount?: null | number;
  amountBase?: null | string;
  amountDistributed?: null | string;
  apr?: null | string;
  baseApr?: null | string;
  baseTvl?: null | string;
  commitTxHash?: string | null;
  createdAt?: string;
  customArgs?: unknown;
  customMetrics?: unknown;
  netTvl?: null | string;
  rewardTokenPrice?: null | string;
  rootHash?: string | null;
  timestamp?: string;
  turtleNetTvl?: null | string;
  turtleTvl?: null | string;
  tvl?: null | string;
  updatedAt?: string;
  userCount?: null | number;
};

export type StreamsSupportedToken = {
  address?: string;
  chainId?: number;
  decimals?: number;
  id?: UuidUuid;
  isAllowedRewardToken?: boolean;
  logoUrl?: string;
  name?: string;
  symbol?: string;
};

export type StreamsWalletData = {
  snapshots?: Array<StreamsWalletSnapshot> | null;
  stream?: StreamsStream;
  streamId?: UuidUuid;
  userAddress?: string | null;
};

export type StreamsWalletSnapshot = {
  apr?: null | string;
  baseApr?: null | string;
  baseTvl?: null | string;
  createdAt?: string;
  customMetrics?: unknown;
  netTvl?: null | string;
  rewardsAccumulated?: string;
  rewardsAccumulatedBase?: string;
  timestamp?: string;
  turtleNetTvl?: null | string;
  turtleTvl?: null | string;
  tvl?: null | string;
  updatedAt?: string;
};

export type StreamsWalletWithLastSnapshot = {
  lastSnapshot?: StreamsWalletSnapshot;
  userAddress?: string;
};

export type TrackingEarnTrackingMetadata = {
  action?: string;
  actionId?: string;
  amount?: string;
  amountUsd?: string;
  distributorId?: string;
  opportunityId?: string;
  referralCode?: string;
  tokenIn?: string;
  tokenInDecimals?: number;
};

export type TypesRouteStep = {
  action?: string;
  from?: TypesTokenDetails;
  to?: TypesTokenDetails;
};

export type TypesSwapMetadata = {
  amountOut?: string;
  gas?: string;
  provider?: string;
  providerImg?: string;
  route?: Array<TypesRouteStep> | null;
};

export type TypesTokenDetails = {
  address?: string;
  decimals?: number;
  logoUrl?: string;
  symbol?: string;
};

export type TypesTransaction = {
  chainId?: number;
  data?: string;
  gasLimit?: string;
  to?: string;
  value?: string;
};

export type TypesTxResponseItem = {
  description?: string;
  metadata?: TypesSwapMetadata;
  transaction?: TypesTransaction;
  type?: string;
};

export type UtilsPaginationResponse = {
  hasNext?: null | boolean;
  hasPrevious?: null | boolean;
  limit?: number;
  page?: number;
  total?: number;
  totalPages?: number;
};

export type UuidUuid = null | string;

export type V1ChainResponse = {
  /**
   * Chain ID for wallet connections
   */
  chainId?: string;
  /**
   * Blockchain ecosystem (e.g. EVM, Solana)
   */
  ecosystem?: string;
  /**
   * Block explorer base URL
   */
  explorerUrl?: string;
  /**
   * Chain unique identifier
   */
  id?: UuidUuid;
  /**
   * Chain logo image URL
   */
  logoUrl?: string;
  /**
   * Chain full name
   */
  name?: string;
  /**
   * Chain URL-friendly identifier
   */
  slug?: string;
  /**
   * Chain operational status
   */
  status?: string;
};

export type V1CreateMembershipAgreementInput = {
  /**
   * Wallet address
   */
  address: string;
  /**
   * Chain ID for EVM wallets
   */
  chainId?: string;
  /**
   * URL for the agreement
   */
  url: string;
  /**
   * Wallet ecosystem
   */
  walletEcosystem: "evm" | "solana" | "ton";
};

export type V1CreateMembershipAgreementOutput = {
  /**
   * Message to be signed
   */
  message?: string;
  /**
   * Nonce for the signature
   */
  nonce?: string;
};

export type V1CreateMembershipInput = {
  address: string;
  distributor_id?: string;
  nonce: string;
  signature: string;
  walletEcosystem: string;
};

export type V1CreateMembershipOutput = {
  /**
   * Error message if any
   */
  error?: string;
  /**
   * Whether the wallet is associated with a user
   */
  isMember?: boolean;
};

export type V1CuratorResponse = {
  /**
   * Curator description
   */
  description?: string;
  /**
   * Curator icon image URL
   */
  iconUrl?: string;
  /**
   * Curator website URL
   */
  landingUrl?: string;
  /**
   * Curator name
   */
  name?: string;
};

export type V1DepositDto = {
  /**
   * Chain ID where deposit occurred
   */
  chain?: number;
  /**
   * USD value of deposit at time of transaction
   */
  deposited_amount_usd?: string;
  /**
   * Contract address of deposited token
   */
  deposited_token_address?: string;
  /**
   * Decimal places of deposited token
   */
  deposited_token_decimals?: number;
  /**
   * Logo URL of deposited token
   */
  deposited_token_logo?: string;
  /**
   * Full name of deposited token
   */
  deposited_token_name?: string;
  /**
   * Symbol of deposited token
   */
  deposited_token_symbol?: string;
  /**
   * Amount deposited in token units
   */
  deposited_value?: string;
  /**
   * Wallet address that made the deposit
   */
  depositor?: string;
  /**
   * Target contract or vault address
   */
  target?: string;
  /**
   * ISO timestamp of deposit transaction
   */
  timestamp?: string;
  /**
   * Transaction hash on blockchain
   */
  tx_hash?: string;
};

export type V1EarnOpportunityResponse = {
  /**
   * Base token for the opportunity
   */
  baseTokens?: V1TokenResponse;
  /**
   * Curator organization for the opportunity
   */
  curator?: V1CuratorResponse;
  /**
   * Tokens accepted for deposit
   */
  depositTokens?: Array<V1TokenResponse> | null;
  /**
   * Opportunity detailed description
   */
  description?: string;
  /**
   * Estimated Annual Percentage Rate
   */
  estimatedApr?: number;
  /**
   * Whether opportunity is featured
   */
  featured?: boolean;
  /**
   * Opportunity unique identifier
   */
  id?: UuidUuid;
  /**
   * Incentives for the opportunity
   */
  incentives?: Array<V1IncentiveResponse> | null;
  /**
   * Minimum deposit amount in USD
   */
  minDepositAmountUsd?: number;
  /**
   * Opportunity display name
   */
  name?: string;
  /**
   * Token received as receipt for deposits
   */
  receiptToken?: V1TokenResponse;
  /**
   * Whether direct deposit mode is enabled
   */
  swapDirectEnabled?: boolean;
  /**
   * Whether swap/route deposit mode is enabled
   */
  swapRouteEnabled?: boolean;
  /**
   * Total Value Locked in USD
   */
  tvl?: number;
  /**
   * Opportunity type (e.g. lending, vault)
   */
  type?: string;
};

export type V1GetDepositsResponse = {
  /**
   * List of deposit transactions
   */
  deposits?: Array<V1DepositDto> | null;
};

export type V1GetMembershipOutput = {
  /**
   * Whether the wallet is associated with a user
   */
  isMember?: boolean;
};

export type V1GetOpportunitiesResponse = {
  /**
   * List of available opportunities
   */
  opportunities?: Array<V1EarnOpportunityResponse> | null;
  /**
   * Total number of opportunities returned
   */
  total?: number;
};

export type V1GetOpportunityByIdResponse = {
  /**
   * Opportunity details
   */
  opportunity?: V1EarnOpportunityResponse;
};

export type V1GetRouteResponse = {
  data?: unknown;
  error?: string;
  exp?: number;
};

export type V1GetSwapDetailsResponse = {
  /**
   * Chains supported by the swap router (intersection of router-supported chains and our chain catalog)
   */
  chains?: Array<V1SwapChain> | null;
  /**
   * Popular tokens for the requested chain. Empty when chainId is omitted
   */
  popularTokens?: Array<V1SwapToken> | null;
};

export type V1GetSwapResponse = {
  /**
   * Unique identifier embedded in the swap tx tracking metadata
   */
  actionId?: UuidUuid;
  /**
   * Ordered list of transactions to execute (approve + swap)
   */
  transactions?: Array<TypesTxResponseItem> | null;
};

export type V1GetSwapTokensResponse = {
  /**
   * Tokens matching the query for the requested chain
   */
  data?: Array<V1SwapToken> | null;
  /**
   * Pagination metadata
   */
  pagination?: UtilsPaginationResponse;
};

export type V1IncentiveResponse = {
  /**
   * Annual Percentage Rate
   */
  apr?: null | number;
  /**
   * Incentive description
   */
  description?: string;
  /**
   * Estimated price in USD
   */
  estPriceUsd?: null | number;
  /**
   * Fully Diluted Valuation estimate
   */
  fdvEstimate?: null | number;
  /**
   * Incentive icon URL
   */
  iconUrl?: string;
  /**
   * Incentive unique identifier
   */
  id?: UuidUuid;
  /**
   * Whether incentive is indexed
   */
  indexed?: boolean;
  /**
   * Maximum Annual Percentage Rate
   */
  maxApr?: null | number;
  /**
   * Minimum Annual Percentage Rate
   */
  minApr?: null | number;
  /**
   * Incentive name
   */
  name?: string;
  /**
   * Type of reward (points, tokens, yield, vesting)
   */
  rewardType?: string;
  /**
   * Human-readable reward type name
   */
  rewardTypeName?: string;
  /**
   * Incentive status (active, paused, ended)
   */
  status?: string;
  /**
   * Token supply allocation percentage
   */
  tokenSupplyAllocation?: null | number;
};

export type V1SwapChain = {
  /**
   * Numeric chain ID
   */
  chainId?: string;
  /**
   * Blockchain ecosystem (evm, solana)
   */
  ecosystem?: string;
  /**
   * Block explorer base URL
   */
  explorerUrl?: string;
  /**
   * Chain logo URL
   */
  logoUrl?: string;
  /**
   * Chain name
   */
  name?: string;
  /**
   * USD price of the chain's native token, used for gas fee math
   */
  nativePriceUsd?: number;
  /**
   * URL-friendly identifier
   */
  slug?: string;
};

export type V1SwapToken = {
  /**
   * Token contract address
   */
  address?: string;
  /**
   * Numeric chain ID this token belongs to
   */
  chainId?: string;
  /**
   * Token decimals
   */
  decimals?: number;
  /**
   * Whether token is native to the chain
   */
  isNative?: boolean;
  /**
   * Token logo URL
   */
  logoUrl?: string;
  /**
   * Token full name
   */
  name?: string;
  /**
   * USD price
   */
  priceUsd?: number;
  /**
   * Token symbol
   */
  symbol?: string;
};

export type V1TokenResponse = {
  /**
   * Token contract address
   */
  address?: string;
  /**
   * Chain information where token exists
   */
  chain?: V1ChainResponse;
  /**
   * Token decimal places
   */
  decimals?: number;
  /**
   * Token unique identifier
   */
  id?: UuidUuid;
  /**
   * Whether token is native to the chain
   */
  isNative?: boolean;
  /**
   * Token logo image URL
   */
  logoUrl?: string;
  /**
   * Token full name
   */
  name?: string;
  /**
   * Token symbol (e.g. USDC, ETH)
   */
  symbol?: string;
};

export type V2AprBreakdown = {
  /**
   * APR from share-price growth alone (simple, non-compound)
   */
  base?: number;
  /**
   * Reward APR; reserved for future rewards indexing, currently always 0
   */
  reward?: number;
  /**
   * base + reward
   */
  total?: number;
};

export type V2ApyBreakdown = {
  /**
   * APY from share-price growth alone (vaults.fyi compound formula)
   */
  base?: number;
  /**
   * Reward APY; reserved for future rewards indexing, currently always 0
   */
  reward?: number;
  /**
   * base + reward
   */
  total?: number;
} | null;

export type V2GetOpportunityHistoricalAprResponse = {
  data?: Array<V2HistoricalAprPoint> | null;
};

export type V2GetOpportunityHistoricalApyResponse = {
  data?: Array<V2HistoricalApyPoint> | null;
};

export type V2GetOpportunityHistoricalResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalCombinedPoint> | null;
  /**
   * true when backend hit the row cap and oldest APY values may be missing predecessors
   */
  historyTruncated?: boolean;
};

export type V2GetOpportunityHistoricalSharePriceResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalSharePricePoint> | null;
};

export type V2GetOpportunityHistoricalTvlResponse = {
  /**
   * null when the vault has not yet been indexed in vault_metrics or the underlying token is not registered in supported_tokens
   */
  baseAsset?: SharedTokenResponse;
  data?: Array<V2HistoricalTvlPoint> | null;
};

export type V2HistoricalAprPoint = {
  /**
   * Adjacent-pair simple-rate APR against the previous bucket
   */
  apr?: V2AprBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2HistoricalApyPoint = {
  /**
   * Adjacent-pair compound APY against the previous bucket
   */
  apy?: V2ApyBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2HistoricalCombinedPoint = {
  /**
   * Trailing-window APY at this bucket; null when no predecessor exists
   */
  apy?: V2ApyBreakdown;
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  sharePrice?: V2NativeUsdValue;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
  tvl?: V2NativeUsdValue;
};

export type V2HistoricalSharePricePoint = {
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  sharePrice?: V2NativeUsdValue;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
};

export type V2HistoricalTvlPoint = {
  /**
   * On-chain block number of the snapshot chosen as the bucket representative
   */
  blockNumber?: number;
  /**
   * Bucket representative time (unix seconds)
   */
  timestamp?: number;
  tvl?: V2NativeUsdValue;
};

export type V2NativeUsdValue = {
  native?: number;
  /**
   * null when underlying USD price was not available for this bucket
   */
  usd?: null | number;
};

export type V2ProtocolResponse = {
  /**
   * Protocol logo image URL
   */
  logoUrl?: string;
  /**
   * Protocol name
   */
  name?: string;
  /**
   * Protocol website URL
   */
  siteUrl?: string;
};

export type AttributeActionData = {
  body?: ActionsAttributeActionRequest;
  path: {
    /**
     * Action unique identifier
     */
    actionId: UuidUuid;
  };
  query?: never;
  url: "/v1/actions/attribute/{actionId}";
};

export type AttributeActionErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type AttributeActionError =
  AttributeActionErrors[keyof AttributeActionErrors];

export type AttributeActionResponses = {
  /**
   * OK
   */
  200: ActionsAttributeActionResponse;
};

export type AttributeActionResponse =
  AttributeActionResponses[keyof AttributeActionResponses];

export type CreateCancelDepositInteractionData = {
  body?: ActionsCancelDepositRequest;
  path: {
    /**
     * Opportunity unique identifier
     */
    opportunityId: UuidUuid;
  };
  query?: never;
  url: "/v1/actions/cancel-deposit/{opportunityId}";
};

export type CreateCancelDepositInteractionErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type CreateCancelDepositInteractionError =
  CreateCancelDepositInteractionErrors[keyof CreateCancelDepositInteractionErrors];

export type CreateCancelDepositInteractionResponses = {
  /**
   * OK
   */
  200: ActionsInteractionResponse;
};

export type CreateCancelDepositInteractionResponse =
  CreateCancelDepositInteractionResponses[keyof CreateCancelDepositInteractionResponses];

export type CreateClaimDepositInteractionData = {
  body?: ActionsClaimDepositRequest;
  path: {
    /**
     * Opportunity unique identifier
     */
    opportunityId: UuidUuid;
  };
  query?: never;
  url: "/v1/actions/claim-deposit/{opportunityId}";
};

export type CreateClaimDepositInteractionErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type CreateClaimDepositInteractionError =
  CreateClaimDepositInteractionErrors[keyof CreateClaimDepositInteractionErrors];

export type CreateClaimDepositInteractionResponses = {
  /**
   * OK
   */
  200: ActionsInteractionResponse;
};

export type CreateClaimDepositInteractionResponse =
  CreateClaimDepositInteractionResponses[keyof CreateClaimDepositInteractionResponses];

export type CreateDepositInteractionData = {
  body?: ActionsInteractionRequest;
  path: {
    /**
     * Opportunity unique identifier
     */
    opportunityId: UuidUuid;
  };
  query?: never;
  url: "/v1/actions/deposit/{opportunityId}";
};

export type CreateDepositInteractionErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type CreateDepositInteractionError =
  CreateDepositInteractionErrors[keyof CreateDepositInteractionErrors];

export type CreateDepositInteractionResponses = {
  /**
   * OK
   */
  200: ActionsInteractionResponse;
};

export type CreateDepositInteractionResponse =
  CreateDepositInteractionResponses[keyof CreateDepositInteractionResponses];

export type VerifyTrackingData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Chain ID where the transaction was executed
     */
    chainId: number;
    /**
     * Transaction hash to verify
     */
    txHash: string;
  };
  url: "/v1/actions/verify";
};

export type VerifyTrackingErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type VerifyTrackingError =
  VerifyTrackingErrors[keyof VerifyTrackingErrors];

export type VerifyTrackingResponses = {
  /**
   * OK
   */
  200: ActionsVerifyTrackingResponse;
};

export type VerifyTrackingResponse =
  VerifyTrackingResponses[keyof VerifyTrackingResponses];

export type CreateWithdrawInteractionData = {
  body?: ActionsWithdrawRequest;
  path: {
    /**
     * Opportunity unique identifier
     */
    opportunityId: UuidUuid;
  };
  query?: never;
  url: "/v1/actions/withdraw/{opportunityId}";
};

export type CreateWithdrawInteractionErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type CreateWithdrawInteractionError =
  CreateWithdrawInteractionErrors[keyof CreateWithdrawInteractionErrors];

export type CreateWithdrawInteractionResponses = {
  /**
   * OK
   */
  200: ActionsInteractionResponse;
};

export type CreateWithdrawInteractionResponse =
  CreateWithdrawInteractionResponses[keyof CreateWithdrawInteractionResponses];

export type GetDepositsData = {
  body?: never;
  path: {
    /**
     * Distributor ID to filter deposits
     */
    distributor_id: string;
  };
  query?: {
    /**
     * Filter by depositor wallet address
     */
    depositor?: null | string;
    /**
     * Maximum number of deposits to return (default: 100, max: 2000)
     */
    limit?: null | number;
    /**
     * Number of deposits to skip for pagination
     */
    offset?: null | number;
  };
  url: "/v1/deposit/{distributor_id}";
};

export type GetDepositsErrors = {
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetDepositsError = GetDepositsErrors[keyof GetDepositsErrors];

export type GetDepositsResponses = {
  /**
   * OK
   */
  200: V1GetDepositsResponse;
};

export type GetDepositsResponse =
  GetDepositsResponses[keyof GetDepositsResponses];

export type GetMembershipData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Wallet address to check
     */
    address?: string;
    /**
     * Wallet ecosystem
     */
    walletEcosystem?: "evm" | "solana" | "ton";
  };
  url: "/v1/membership/";
};

export type GetMembershipResponses = {
  /**
   * OK
   */
  200: V1GetMembershipOutput;
};

export type GetMembershipResponse =
  GetMembershipResponses[keyof GetMembershipResponses];

export type MembershipCreateData = {
  body?: V1CreateMembershipInput;
  path?: never;
  query?: never;
  url: "/v1/membership/";
};

export type MembershipCreateErrors = {
  /**
   * Conflict
   */
  409: RestErrResponse;
};

export type MembershipCreateError =
  MembershipCreateErrors[keyof MembershipCreateErrors];

export type MembershipCreateResponses = {
  /**
   * OK
   */
  200: V1CreateMembershipOutput;
};

export type MembershipCreateResponse =
  MembershipCreateResponses[keyof MembershipCreateResponses];

export type CreateMembershipAgreementData = {
  body?: V1CreateMembershipAgreementInput;
  path?: never;
  query?: never;
  url: "/v1/membership/agreement";
};

export type CreateMembershipAgreementErrors = {
  /**
   * Conflict
   */
  409: RestErrResponse;
};

export type CreateMembershipAgreementError =
  CreateMembershipAgreementErrors[keyof CreateMembershipAgreementErrors];

export type CreateMembershipAgreementResponses = {
  /**
   * OK
   */
  200: V1CreateMembershipAgreementOutput;
};

export type CreateMembershipAgreementResponse =
  CreateMembershipAgreementResponses[keyof CreateMembershipAgreementResponses];

export type GetOpportunitiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Comma-separated list of chain IDs to filter by
     */
    chainIds?: string;
    /**
     * Deposit token in format 'address-chainId' (e.g., '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7-43114')
     */
    depositToken?: string;
    /**
     * Filter opportunities with TVL greater than this value
     */
    tvlGreaterThan?: number;
  };
  url: "/v1/opportunities/";
};

export type GetOpportunitiesErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetOpportunitiesError =
  GetOpportunitiesErrors[keyof GetOpportunitiesErrors];

export type GetOpportunitiesResponses = {
  /**
   * OK
   */
  200: V1GetOpportunitiesResponse;
};

export type GetOpportunitiesResponse =
  GetOpportunitiesResponses[keyof GetOpportunitiesResponses];

export type GetOpportunitiesByDistributorData = {
  body?: never;
  path: {
    /**
     * Distributor ID to filter opportunities
     */
    distributor_id: string;
  };
  query?: never;
  url: "/v1/opportunities/distributors/{distributor_id}";
};

export type GetOpportunitiesByDistributorErrors = {
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetOpportunitiesByDistributorError =
  GetOpportunitiesByDistributorErrors[keyof GetOpportunitiesByDistributorErrors];

export type GetOpportunitiesByDistributorResponses = {
  /**
   * OK
   */
  200: V1GetOpportunitiesResponse;
};

export type GetOpportunitiesByDistributorResponse =
  GetOpportunitiesByDistributorResponses[keyof GetOpportunitiesByDistributorResponses];

export type GetOpportunityByIdData = {
  body?: never;
  path: {
    /**
     * Opportunity unique identifier
     */
    id: UuidUuid;
  };
  query?: never;
  url: "/v1/opportunities/{id}";
};

export type GetOpportunityByIdErrors = {
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetOpportunityByIdError =
  GetOpportunityByIdErrors[keyof GetOpportunityByIdErrors];

export type GetOpportunityByIdResponses = {
  /**
   * OK
   */
  200: V1GetOpportunityByIdResponse;
};

export type GetOpportunityByIdResponse =
  GetOpportunityByIdResponses[keyof GetOpportunityByIdResponses];

export type GetEarnRouteData = {
  body?: never;
  path?: never;
  query: {
    /**
     * The user's EOA address initiating the transaction
     */
    user: string;
    /**
     * The chain ID for the transaction
     */
    chain: number;
    /**
     * Acceptable slippage tolerance (0.001-0.5)
     */
    slippage: number;
    /**
     * Input token address or 'native'
     */
    token_in: string;
    /**
     * Output token address
     */
    token_out: string;
    /**
     * Amount to trade in smallest unit
     */
    amount: string;
    /**
     * Distributor ID for the transaction
     */
    distributor_id: string;
    /**
     * Optional referral code
     */
    referral_code?: string;
  };
  url: "/v1/route/";
};

export type GetEarnRouteErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetEarnRouteError = GetEarnRouteErrors[keyof GetEarnRouteErrors];

export type GetEarnRouteResponses = {
  /**
   * OK
   */
  200: V1GetRouteResponse;
};

export type GetEarnRouteResponse =
  GetEarnRouteResponses[keyof GetEarnRouteResponses];

export type V1StreamsGetStreamsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    id?: UuidUuid;
    withSnapshots?: boolean;
    usersCount?: boolean;
  };
  url: "/v1/streams/";
};

export type V1StreamsGetStreamsHandlerErrors = {
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsGetStreamsHandlerError =
  V1StreamsGetStreamsHandlerErrors[keyof V1StreamsGetStreamsHandlerErrors];

export type V1StreamsGetStreamsHandlerResponses = {
  /**
   * OK
   */
  200: StreamsGetStreamsOutput;
};

export type V1StreamsGetStreamsHandlerResponse =
  V1StreamsGetStreamsHandlerResponses[keyof V1StreamsGetStreamsHandlerResponses];

export type V1StreamsCreateStreamHandlerData = {
  body?: StreamsCreateStreamRequestParams;
  path?: never;
  query?: never;
  url: "/v1/streams/";
};

export type V1StreamsCreateStreamHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Forbidden
   */
  403: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsCreateStreamHandlerError =
  V1StreamsCreateStreamHandlerErrors[keyof V1StreamsCreateStreamHandlerErrors];

export type V1StreamsCreateStreamHandlerResponses = {
  /**
   * OK
   */
  200: StreamsCreateStreamOutput;
};

export type V1StreamsCreateStreamHandlerResponse =
  V1StreamsCreateStreamHandlerResponses[keyof V1StreamsCreateStreamHandlerResponses];

export type V1StreamsGetPointsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    id?: UuidUuid;
    symbol?: string;
    name?: string;
  };
  url: "/v1/streams/points";
};

export type V1StreamsGetPointsHandlerErrors = {
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsGetPointsHandlerError =
  V1StreamsGetPointsHandlerErrors[keyof V1StreamsGetPointsHandlerErrors];

export type V1StreamsGetPointsHandlerResponses = {
  /**
   * OK
   */
  200: StreamsGetPointsOutput;
};

export type V1StreamsGetPointsHandlerResponse =
  V1StreamsGetPointsHandlerResponses[keyof V1StreamsGetPointsHandlerResponses];

export type V1StreamsCreatePointHandlerData = {
  body?: StreamsCreatePointInput;
  path?: never;
  query?: never;
  url: "/v1/streams/points";
};

export type V1StreamsCreatePointHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsCreatePointHandlerError =
  V1StreamsCreatePointHandlerErrors[keyof V1StreamsCreatePointHandlerErrors];

export type V1StreamsCreatePointHandlerResponses = {
  /**
   * OK
   */
  200: StreamsCreatePointOutput;
};

export type V1StreamsCreatePointHandlerResponse =
  V1StreamsCreatePointHandlerResponses[keyof V1StreamsCreatePointHandlerResponses];

export type V1StreamsGetTokensHandlerData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Decimal chain ID
     */
    chainId: number;
  };
  url: "/v1/streams/tokens";
};

export type V1StreamsGetTokensHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsGetTokensHandlerError =
  V1StreamsGetTokensHandlerErrors[keyof V1StreamsGetTokensHandlerErrors];

export type V1StreamsGetTokensHandlerResponses = {
  /**
   * OK
   */
  200: StreamsGetTokensOutput;
};

export type V1StreamsGetTokensHandlerResponse =
  V1StreamsGetTokensHandlerResponses[keyof V1StreamsGetTokensHandlerResponses];

export type V1StreamsGetWalletsHandlerData = {
  body?: never;
  path: {
    id: UuidUuid;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/v1/streams/{id}/wallets";
};

export type V1StreamsGetWalletsHandlerErrors = {
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsGetWalletsHandlerError =
  V1StreamsGetWalletsHandlerErrors[keyof V1StreamsGetWalletsHandlerErrors];

export type V1StreamsGetWalletsHandlerResponses = {
  /**
   * OK
   */
  200: StreamsGetWalletsOutput;
};

export type V1StreamsGetWalletsHandlerResponse =
  V1StreamsGetWalletsHandlerResponses[keyof V1StreamsGetWalletsHandlerResponses];

export type V1StreamsGetWalletHandlerData = {
  body?: never;
  path: {
    id: UuidUuid;
    address: string;
  };
  query?: never;
  url: "/v1/streams/{id}/wallets/{address}";
};

export type V1StreamsGetWalletHandlerErrors = {
  /**
   * Unauthorized
   */
  401: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type V1StreamsGetWalletHandlerError =
  V1StreamsGetWalletHandlerErrors[keyof V1StreamsGetWalletHandlerErrors];

export type V1StreamsGetWalletHandlerResponses = {
  /**
   * OK
   */
  200: StreamsGetWalletOutput;
};

export type V1StreamsGetWalletHandlerResponse =
  V1StreamsGetWalletHandlerResponses[keyof V1StreamsGetWalletHandlerResponses];

export type GetEarnSwapData = {
  body?: never;
  path?: never;
  query: {
    /**
     * User's EOA address initiating the swap
     */
    user: string;
    /**
     * Chain ID for the swap
     */
    chain: number;
    /**
     * Distributor ID
     */
    distributor_id: string;
    /**
     * Input token address or 'native' alias
     */
    token_in: string;
    /**
     * Output token address or 'native' alias
     */
    token_out: string;
    /**
     * Input amount in smallest unit (wei)
     */
    amount_in: string;
    /**
     * Slippage tolerance in basis points (e.g., 50 = 0.5%)
     */
    slippage_bps: number;
  };
  url: "/v1/swap/";
};

export type GetEarnSwapErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetEarnSwapError = GetEarnSwapErrors[keyof GetEarnSwapErrors];

export type GetEarnSwapResponses = {
  /**
   * OK
   */
  200: V1GetSwapResponse;
};

export type GetEarnSwapResponse =
  GetEarnSwapResponses[keyof GetEarnSwapResponses];

export type GetSwapDetailsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional chain ID to scope the popular tokens list
     */
    chainId?: number;
  };
  url: "/v1/swap/details";
};

export type GetSwapDetailsErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetSwapDetailsError =
  GetSwapDetailsErrors[keyof GetSwapDetailsErrors];

export type GetSwapDetailsResponses = {
  /**
   * OK
   */
  200: V1GetSwapDetailsResponse;
};

export type GetSwapDetailsResponse =
  GetSwapDetailsResponses[keyof GetSwapDetailsResponses];

export type GetSwapTokensData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Numeric chain ID to scope the search
     */
    chainId: number;
    /**
     * Optional search term: matches token symbol, name, or address (case-insensitive partial)
     */
    search?: string;
    /**
     * 1-based page number; defaults to 1
     */
    page?: number;
    /**
     * Page size; defaults to 20, max 300
     */
    limit?: number;
  };
  url: "/v1/swap/tokens";
};

export type GetSwapTokensErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetSwapTokensError = GetSwapTokensErrors[keyof GetSwapTokensErrors];

export type GetSwapTokensResponses = {
  /**
   * OK
   */
  200: V1GetSwapTokensResponse;
};

export type GetSwapTokensResponse =
  GetSwapTokensResponses[keyof GetSwapTokensResponses];

export type GetWalletActivityData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    /**
     * Comma-separated list of EVM wallet addresses to fetch activity for (max 1000)
     */
    addresses?: string;
  };
  url: "/v1/wallets/activity/";
};

export type GetWalletActivityErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type GetWalletActivityError =
  GetWalletActivityErrors[keyof GetWalletActivityErrors];

export type GetWalletActivityResponses = {
  /**
   * OK
   */
  200: ActionsWalletActivityResponse;
};

export type GetWalletActivityResponse =
  GetWalletActivityResponses[keyof GetWalletActivityResponses];

export type HandlersV2GetChainsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/v2/chains/";
};

export type HandlersV2GetChainsHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetChainsHandlerError =
  HandlersV2GetChainsHandlerErrors[keyof HandlersV2GetChainsHandlerErrors];

export type HandlersV2GetChainsHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedChainResponse;
};

export type HandlersV2GetChainsHandlerResponse =
  HandlersV2GetChainsHandlerResponses[keyof HandlersV2GetChainsHandlerResponses];

export type HandlersV2GetOpportunityHistoricalHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical";
};

export type HandlersV2GetOpportunityHistoricalHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalHandlerError =
  HandlersV2GetOpportunityHistoricalHandlerErrors[keyof HandlersV2GetOpportunityHistoricalHandlerErrors];

export type HandlersV2GetOpportunityHistoricalHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalResponse;
};

export type HandlersV2GetOpportunityHistoricalHandlerResponse =
  HandlersV2GetOpportunityHistoricalHandlerResponses[keyof HandlersV2GetOpportunityHistoricalHandlerResponses];

export type HandlersV2GetOpportunityHistoricalAprHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apr";
};

export type HandlersV2GetOpportunityHistoricalAprHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalAprHandlerError =
  HandlersV2GetOpportunityHistoricalAprHandlerErrors[keyof HandlersV2GetOpportunityHistoricalAprHandlerErrors];

export type HandlersV2GetOpportunityHistoricalAprHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalAprResponse;
};

export type HandlersV2GetOpportunityHistoricalAprHandlerResponse =
  HandlersV2GetOpportunityHistoricalAprHandlerResponses[keyof HandlersV2GetOpportunityHistoricalAprHandlerResponses];

export type HandlersV2GetOpportunityHistoricalApyHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/apy";
};

export type HandlersV2GetOpportunityHistoricalApyHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalApyHandlerError =
  HandlersV2GetOpportunityHistoricalApyHandlerErrors[keyof HandlersV2GetOpportunityHistoricalApyHandlerErrors];

export type HandlersV2GetOpportunityHistoricalApyHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalApyResponse;
};

export type HandlersV2GetOpportunityHistoricalApyHandlerResponse =
  HandlersV2GetOpportunityHistoricalApyHandlerResponses[keyof HandlersV2GetOpportunityHistoricalApyHandlerResponses];

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/share-price";
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerError =
  HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors[keyof HandlersV2GetOpportunityHistoricalSharePriceHandlerErrors];

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalSharePriceResponse;
};

export type HandlersV2GetOpportunityHistoricalSharePriceHandlerResponse =
  HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses[keyof HandlersV2GetOpportunityHistoricalSharePriceHandlerResponses];

export type HandlersV2GetOpportunityHistoricalTvlHandlerData = {
  body?: never;
  path: {
    /**
     * EVM chain ID (e.g. 1 for Ethereum)
     */
    chainId: number;
    /**
     * 0x-prefixed 40-hex vault contract address
     */
    vaultAddress: string;
  };
  query?: {
    /**
     * Bucket width in seconds. Defaults to 86400 (1 day)
     */
    intervalSeconds?: number;
    /**
     * Unix seconds, inclusive. Defaults to now - 30d when omitted
     */
    fromTimestamp?: number;
    /**
     * Unix seconds, inclusive. Defaults to now when omitted
     */
    toTimestamp?: number;
  };
  url: "/v2/opportunities/{chainId}/{vaultAddress}/historical/tvl";
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerError =
  HandlersV2GetOpportunityHistoricalTvlHandlerErrors[keyof HandlersV2GetOpportunityHistoricalTvlHandlerErrors];

export type HandlersV2GetOpportunityHistoricalTvlHandlerResponses = {
  /**
   * OK
   */
  200: V2GetOpportunityHistoricalTvlResponse;
};

export type HandlersV2GetOpportunityHistoricalTvlHandlerResponse =
  HandlersV2GetOpportunityHistoricalTvlHandlerResponses[keyof HandlersV2GetOpportunityHistoricalTvlHandlerResponses];

export type HandlersV2GetProtocolsHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/v2/protocols/";
};

export type HandlersV2GetProtocolsHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetProtocolsHandlerError =
  HandlersV2GetProtocolsHandlerErrors[keyof HandlersV2GetProtocolsHandlerErrors];

export type HandlersV2GetProtocolsHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2ProtocolResponse;
};

export type HandlersV2GetProtocolsHandlerResponse =
  HandlersV2GetProtocolsHandlerResponses[keyof HandlersV2GetProtocolsHandlerResponses];

export type HandlersV2GetTokensHandlerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    /**
     * Filter by numeric chain ID
     */
    chainId?: number;
    /**
     * Case-insensitive partial match across address, name and symbol
     */
    search?: string;
  };
  url: "/v2/tokens/";
};

export type HandlersV2GetTokensHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetTokensHandlerError =
  HandlersV2GetTokensHandlerErrors[keyof HandlersV2GetTokensHandlerErrors];

export type HandlersV2GetTokensHandlerResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseGithubComTurtleDaoTurtlePartnersGoServicesEarnHandlersV2SharedTokenResponse;
};

export type HandlersV2GetTokensHandlerResponse =
  HandlersV2GetTokensHandlerResponses[keyof HandlersV2GetTokensHandlerResponses];

export type HandlersV2GetTokenByAddressHandlerData = {
  body?: never;
  path: {
    /**
     * Numeric chain ID
     */
    chainId: number;
    /**
     * Token contract address (case-insensitive)
     */
    address: string;
  };
  query?: never;
  url: "/v2/tokens/{chainId}/{address}";
};

export type HandlersV2GetTokenByAddressHandlerErrors = {
  /**
   * Bad Request
   */
  400: RestErrResponse;
  /**
   * Not Found
   */
  404: RestErrResponse;
  /**
   * Internal Server Error
   */
  500: RestErrResponse;
};

export type HandlersV2GetTokenByAddressHandlerError =
  HandlersV2GetTokenByAddressHandlerErrors[keyof HandlersV2GetTokenByAddressHandlerErrors];

export type HandlersV2GetTokenByAddressHandlerResponses = {
  /**
   * OK
   */
  200: SharedTokenResponse;
};

export type HandlersV2GetTokenByAddressHandlerResponse =
  HandlersV2GetTokenByAddressHandlerResponses[keyof HandlersV2GetTokenByAddressHandlerResponses];
