// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemResponses,
  ListAllItemsData,
  ListAllItemsResponses,
  ListSprocketsData,
  ListSprocketsResponses,
  ListWidgetsData,
  ListWidgetsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List items
 */
export const listAllItems = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllItemsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListAllItemsResponses, unknown, ThrowOnError>(
    { url: "/v1/items", ...options },
  );

/**
 * Create item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateItemResponses, unknown, ThrowOnError>({
    url: "/v1/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Auto-added listWidgets
 */
export const listWidgets = <ThrowOnError extends boolean = false>(
  options?: Options<ListWidgetsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListWidgetsResponses, unknown, ThrowOnError>({
    url: "/v1/widgets",
    ...options,
  });

/**
 * Auto-added listSprockets
 */
export const listSprockets = <ThrowOnError extends boolean = false>(
  options?: Options<ListSprocketsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSprocketsResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/sprockets", ...options });
