// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemResponses,
  ListCogsData,
  ListCogsResponses,
  ListGizmosData,
  ListGizmosResponses,
  ListSprocketsV2Data,
  ListSprocketsV2Responses,
  TurtleDemoData,
  TurtleDemoResponses,
} from "./types.gen";
import {
  zCreateItemBody,
  zCreateItemResponse,
  zListCogsResponse,
  zListGizmosResponse,
  zListSprocketsV2Response,
  zTurtleDemoResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List items
 */
export const turtleDemo = <ThrowOnError extends boolean = false>(
  options?: Options<TurtleDemoData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TurtleDemoResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zTurtleDemoResponse.parseAsync(data),
    url: "/v1/items",
    ...options,
  });

/**
 * Create item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateItemResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateItemBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zCreateItemResponse.parseAsync(data),
    url: "/v1/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Auto-added listGizmos
 */
export const listGizmos = <ThrowOnError extends boolean = false>(
  options?: Options<ListGizmosData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListGizmosResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zListGizmosResponse.parseAsync(data),
    url: "/v1/gizmos",
    ...options,
  });

/**
 * Auto-added listCogs
 */
export const listCogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListCogsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListCogsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zListCogsResponse.parseAsync(data),
    url: "/v1/cogs",
    ...options,
  });

/**
 * Auto-added listSprocketsV2
 */
export const listSprocketsV2 = <ThrowOnError extends boolean = false>(
  options?: Options<ListSprocketsV2Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSprocketsV2Responses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zListSprocketsV2Response.parseAsync(data),
    url: "/v1/sprockets-v2",
    ...options,
  });
