// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://fake.local" | (string & {});
};

export type Item = {
  id: string;
  name: string;
  createdAt?: string;
};

export type ItemInput = {
  name: string;
};

export type ListItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/items";
};

export type ListItemsResponses = {
  /**
   * OK
   */
  200: Array<Item>;
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type CreateItemData = {
  body: ItemInput;
  path?: never;
  query?: never;
  url: "/v1/items";
};

export type CreateItemResponses = {
  /**
   * Created
   */
  201: Item;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type GetItemData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v1/items/{id}";
};

export type GetItemErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemResponses = {
  /**
   * OK
   */
  200: Item;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type ListWidgetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/widgets";
};

export type ListWidgetsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListWidgetsResponse =
  ListWidgetsResponses[keyof ListWidgetsResponses];

export type ListSprocketsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/sprockets";
};

export type ListSprocketsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListSprocketsResponse =
  ListSprocketsResponses[keyof ListSprocketsResponses];
