// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://fake.local" | (string & {});
};

export type Item = {
  id: string;
  name: string;
  createdAt?: string;
};

export type ItemInput = {
  name: string;
};

export type TurtleAmazingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/items";
};

export type TurtleAmazingResponses = {
  /**
   * OK
   */
  200: Array<Item>;
};

export type TurtleAmazingResponse =
  TurtleAmazingResponses[keyof TurtleAmazingResponses];

export type CreateItemData = {
  body: ItemInput;
  path?: never;
  query?: never;
  url: "/v1/items";
};

export type CreateItemResponses = {
  /**
   * Created
   */
  201: Item;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type ListWidgetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/widgets";
};

export type ListWidgetsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListWidgetsResponse =
  ListWidgetsResponses[keyof ListWidgetsResponses];

export type ListSprocketsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/sprockets";
};

export type ListSprocketsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListSprocketsResponse =
  ListSprocketsResponses[keyof ListSprocketsResponses];

export type ListGizmosData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/gizmos";
};

export type ListGizmosResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListGizmosResponse = ListGizmosResponses[keyof ListGizmosResponses];

export type ListCogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/cogs";
};

export type ListCogsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListCogsResponse = ListCogsResponses[keyof ListCogsResponses];

export type ListSprocketsV2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/sprockets-v2";
};

export type ListSprocketsV2Responses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListSprocketsV2Response =
  ListSprocketsV2Responses[keyof ListSprocketsV2Responses];
