// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zItem = z.object({
  id: z.string(),
  name: z.string(),
  createdAt: z.iso.datetime().optional(),
});

export const zItemInput = z.object({
  name: z.string(),
});

/**
 * OK
 */
export const zListAllItemsResponse = z.array(zItem);

export const zCreateItemBody = zItemInput;

/**
 * Created
 */
export const zCreateItemResponse = zItem;

/**
 * OK
 */
export const zListWidgetsResponse = z.record(z.string(), z.unknown());

/**
 * OK
 */
export const zListSprocketsResponse = z.record(z.string(), z.unknown());

/**
 * OK
 */
export const zListGizmosResponse = z.record(z.string(), z.unknown());
